### ISSUE TITLE
Product metadata format transformation 

### ISSUE THREAD

**Issue by HengJiang0206** [NYCPlanning/data-engineering#1013]
Explore packages and approaches to transform metadata formats from YAML to PDF, potentially with custom formatting options (fonts and mages). This could involve a mix of packages (readme/text builder or other combinations), from intermediate Python objects to PDF. 

Criteria for package selection 
- Functionality (do what we need)
- Decent user base and well-regarded
- Good documentation 

Once there is a shortlist of options, compare them based on ease of use, reference code snippets, and examples of their API.   

Sample Metadata: https://github.com/NYCPlanning/product-metadata/blob/main/products/pluto/pluto/metadata.yml

**Comment by HengJiang0206** [comment]
### Attempted the approach to convert `yaml` to `md` to `pdf`:

- Convert `yaml` to `md` with package `yaml-to-markdown`:  https://socket.dev/pypi/package/yaml-to-markdown
- run command `yaml-to-markdown --output-file output.md --yaml-file test.yaml`
- Convert `md` to `pdf` with `pandoc`: https://pandoc.org/MANUAL.html
- run command `pandoc metadata.md -V geometry:margin=1in -o output.pdf` (could pass in more arguments or create css config files for customization, insert images, etc).

**Comment by damonmcc** [comment]
noting that this is related to https://github.com/NYCPlanning/data-engineering/issues/944
