### ISSUE TITLE
CPDB enhancements

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#102]
[Project Statement](https://nyco365.sharepoint.com/:w:/r/sites/NYCPLANNING/itd/edm/_layouts/15/doc2.aspx?sourcedoc=%7Bad134f75-e828-4efe-a7ea-0dcb0bb01c1f%7D&action=edit)

**Comment by damonmcc** [comment]
awaiting review of draft [Project Statement](https://nyco365.sharepoint.com/:w:/r/sites/NYCPLANNING/itd/edm/_layouts/15/doc2.aspx?sourcedoc=%7Bad134f75-e828-4efe-a7ea-0dcb0bb01c1f%7D&action=edit) to then finish and share with Capital Planning team for confirmation

**Comment by damonmcc** [comment]
awaiting Capital Planning feedback on project statement

**Comment by damonmcc** [comment]
from KW/Capital Planning on 9/12:

some questions and comments we’re hoping to cover:

- CPDB FISA commitments/liquidations data improvements
- In which tables will the new columns be included?
- Projects, commitments
- Will new columns be replacing any columns, or are we just adding new columns?
- How does this change
  - Citycost
  - Totalcost
  - CCexempt
  - CCnonexempt
  - Totalcityplannedcomit
  - Totalplannedcommit
- Will EDM still be including CheckbookNYC information?
- Should naming convention include underscores to improve readability?
- How are column naming conventions influenced by GIS column name character limits?
- How should we let DE know what the descriptions in the data dictionary should be?
- Can you please also include NYCHA developments shapefiles in the mapping process? Currently projects at NYCHA developments are not mapped against the FacDB or any other spatial reference.

 

Over the longer term, we’d also like to improve our understanding of fuzzy string matching to ultimately work with agencies to improve their naming conventions and increase the % of projects that are mapped

- What is the hierarchy of shapefiles that are used for fuzzy string matching?
- How easy is it to update the CPDB build to include new shapefiles for mapping purposes?
- Can we update the algorithm use sponsor agency for agency ID to improve fuzzy string matching (ie. NYPL as sponsor agency assumes all projects are linked to libraries)
- Are parks capital projects compared not only to their capital project shapefile but to FacDB as well?
- How can we support outreach on Capital Planning’s end to improve naming conventions and increase our mapping?

 Helpful links:

-  [ CPDB unmapped spreadsheet](https://gcc02.safelinks.protection.outlook.com/ap/x-59584e83/?url=https%3A%2F%2Fnyco365.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2FNYCPLANNING%2Fcp%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257BED51D235-222F-4360-BF24-B430286BC8B9%257D%26file%3DCPDB_unmapped_projects_cpe202304_exec.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue&data=05%7C01%7CDMcCullough%40planning.nyc.gov%7Cc0af2739853a453e7ae008dbb39e9c93%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638301266030271908%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0n2Wk42v%2Fjcz%2BGTtSgFh4vic3DGPqkzgde2is4MiyXM%3D&reserved=0) 
- [Medium blog post](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmedium.com%2Fnyc-planning-digital%2Fwelcome-to-the-world-dcps-capital-projects-database-693a8b9782achttps%3A%2Fmedium.com%2Fnyc-planning-digital%2Fwelcome-to-the-world-dcps-capital-projects-database-693a8b9782ac&data=05%7C01%7CDMcCullough%40planning.nyc.gov%7Cc0af2739853a453e7ae008dbb39e9c93%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638301266030271908%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JfssbKZC4STApnOAnUK%2BujNNQN78Q2LcD71RgkpcU94%3D&reserved=0): Join on geometries from spatial datasets of capital projects provided by agency partners or made available on Open Data. DDC, the Economic Development Corporation (EDC), and Department of Transportation (DOT) all provide spatial datasets of their capital projects to DCP. Additionally DOT and the Department of Parks and Recreation (DPR) publish spatial datasets of their capital projects on Open Data. Given that all of these datasets have an FMS ID, which is the unique ID in CPDB, we’re able to easily join on the spatial data. 
- [Github Data Dictionary](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNYCPlanning%2Fdb-cpdb%2Fwiki%2FData-Dictionary&data=05%7C01%7CDMcCullough%40planning.nyc.gov%7Cc0af2739853a453e7ae008dbb39e9c93%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638301266030271908%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9FewwhVtutZ62C0Qv1HcaKrIE%2B5l5pHz0MmTfi2b6qU%3D&reserved=0) 
- ​[ FISA Data Dictionary](https://gcc02.safelinks.protection.outlook.com/ap/x-59584e83/?url=https%3A%2F%2Fnyco365.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2FNYCPLANNING%2Fcp%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B51715C57-143B-454D-983C-9611643A305D%257D%26file%3DProposed%2520FISA%2520data%2520dictionary.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue&data=05%7C01%7CDMcCullough%40planning.nyc.gov%7Cc0af2739853a453e7ae008dbb39e9c93%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638301266030271908%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2TYwqpwFHzCJWKrqWRhHoJTNPgKE1JBARdiL9jMn%2Bl4%3D&reserved=0)
- ​[ Project Statement](https://gcc02.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fnyco365.sharepoint.com%2F%3Aw%3A%2Fr%2Fsites%2FNYCPLANNING%2Fitd%2Fedm%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257BAD134F75-E828-4EFE-A7EA-0DCB0BB01C1F%257D%26file%3DProject%2520statement%2520-%2520Adding%2520new%2520FISA%2520data%2520to%2520CPDB.docx%26action%3Ddefault%26mobileredirect%3Dtrue%26CID%3DF45C6ED0-6C4C-4DB3-A6D6-F1376849A584&data=05%7C01%7CDMcCullough%40planning.nyc.gov%7Cc0af2739853a453e7ae008dbb39e9c93%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C638301266030271908%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VZphMB3C7eQz66MDCgRAT%2B71NJDdRRHDkWwcaMfBuGk%3D&reserved=0)

**Comment by damonmcc** [comment]
notes from chat
- what does each output file represent?
- which files go to OpenData, CPE, and Internal?
- which files will get the new columns? both commitment and project files?
- current
  - Allocation: from FISA -> Commitments: we don't have it -> Liquidations: from CheckbookNYC
- proposed
  - **all 3 coming from FISA**
- save project mapping improvement for 2024 Prelim
  - by using more source geometry shapefiles (e.g. NYCHA)
  - via fuzzy string matching
  - via agencies improving data they put in FMS
  - a hierarchy of mapping (e.g. borough, CD, polygon)

DE todos
- [ ] update wiki to describe output files
- [ ] update project statement

**Comment by mbh329** [comment]
Thanks for this @damonmcc! I can get KW up to speed on Github and we can utilize the issues to keep track of the CPDB progress, communicate between teams, etc. I think best practice would be to just tag us each time as we don't use Github everyday

**Comment by mbh329** [comment]
Until that point, Ill duplicate my comments on the sheet and here so everyone can keep track. For the column names, we can drop the `_` and stick with the column conventions already established in cpdb. I saw in the wiki that the column names are typically 10 characters or less. Not having the underscore in each column name will help shorten them but I can take a stab at keeping them under 10. Does that work for you? Let me know what you think @damonmcc

**Comment by damonmcc** [comment]
that works!

**Comment by damonmcc** [comment]
@mbh329 I've updated [the CPDB wiki](https://github.com/NYCPlanning/data-engineering/wiki/Product:-CPDB#build-outputs) with (very) short descriptions of all outputs

**Comment by mbh329** [comment]
@damonmcc sorry apparently I turned off my emails from github, Ill turn those on again and make sure to check this issue. I noticed this went to backlog. Do we want to touch base on this? I am speaking with Kelsey later today and can check in tomorrow with you.

**Comment by damonmcc** [comment]
on-going discussion around schema with Amanda and Capital Planning
