### ISSUE TITLE
Q3 Opendata Automation Parent Issue

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#1043]

**Comment by alexrichey** [comment]
### August 2, 2024 Meeting Agenda

#### Updates since last
- Paused on further automations
- @HengJiang0206  has started on generating our own Data Dictionaries, working with Design Fellows
- Packaging from Bytes 
  - Next time, packaging LION will be immediate. 
- Refactor for metadata v0 -> v1
  - Generalizing/Opening up for other agencies. 
  - Setting up system to migrate yaml, similar to a database
- First batch of socrata pages to migrate. (Q: review process?)

### TODO these two weeks
- June OpenData
- Continuing on with next datasets (Q: which ones?)
- Continue refactor from v0 to v1

**Comment by damonmcc** [comment]
🎊
