### ISSUE TITLE
GIS + DE workflow for draft reviews

### ISSUE THREAD

**Issue by sf-dcp** [NYCPlanning/data-engineering#1049]
[Related discussion](https://github.com/NYCPlanning/data-engineering/issues/785)

Now that new DO folder structure is implemented, need to figure out and implement a process for QA.

### Proposition (to be discussed with GIS):
1. We create a main GH issue (aka parent issue) for a specific product version. Example: [PLUTO 24v3](https://github.com/NYCPlanning/data-engineering/issues/976#issuecomment-2289438450). 
   * DE uses it to track data loading, building a product, qa'ing, packaging, and distributing.
   * GIS uses it to discuss their QA results (success or failure)
2. When we promote a build to `draft` folder, automatically create a "child" GH issue for GIS to QA the draft. 
   * The issue is assigned to GIS
   * It will contain draft details (draft name, s3 link, streamlit link)
3. When QA is complete (whether it passed or failed), GIS closes the child issue and summarizes results in the parent issue.
4. DE either: 
   * publishes the draft IF it passed GIS QA 
   * builds new draft IF it failed. The process repeats from step 2.

 ```mermaid
flowchart TB

create_parent["Create parent issue\nEx: 'Pluto 24v3'"]
promote_to_draft_1["Create & promote build 1 to 'draft' folder"]
promote_to_draft_2["Create & promote build 2 to 'draft' folder"]
create_child_1["Create child issue 'GIS QA review 1'"]
close_child_1["GIS to close child issue 1"]
close_child_2["GIS to close child issue 2"]
qa_notes_1{"QA approved?"}
de_to_publish["DE to publish draft"]
create_child_2["Create child issue 'GIS QA review 2'"]
and{"..."}

create_parent --> promote_to_draft_1
promote_to_draft_1 --> create_child_1
create_child_1 --> close_child_1
close_child_1 --> qa_notes_1
qa_notes_1 --> |Yes| de_to_publish
qa_notes_1 --> |No| promote_to_draft_2
promote_to_draft_2 --> create_child_2
create_child_2 --> close_child_2
close_child_2 --> and
```

**Comment by damonmcc** [comment]
love it! a couple thoughts:
- I think u could drop the diamond for `GIS QA 1` and change `Close child issue 1` to a box since it's an action, not a decision point
- `automatically create a "child" GH issue for GIS to QA the draft` does seem like a good long-term goal! but in the near-term DE can also easily create the issue by clicking "convert to issue" next to a checkbox in the parent issue
- after `QA approved? --No-->` , I think the next step would be something like `DE run build -> DE Promote build to 'draft' folder -> ...`

**Comment by sf-dcp** [comment]
Modifying the flowchart here: 

 ```mermaid
flowchart TB

create_parent["Create parent issue\nEx: 'Pluto 24v3'"]
promote_to_draft_1["Create & promote build 1 to 'draft' folder"]
promote_to_draft_2["Create & promote build 2 to 'draft' folder"]
create_child_1["Create child issue 'GIS QA review 1'"]
close_child_1["GIS to close child issue 1"]
close_child_2["GIS to close child issue 2"]
qa_notes_1{"QA approved?"}
de_to_publish["DE to publish draft"]
create_child_2["Create child issue 'GIS QA review 2'"]
and{"..."}

create_parent --> promote_to_draft_1
promote_to_draft_1 --> create_child_1
create_child_1 --> close_child_1
close_child_1 --> qa_notes_1
qa_notes_1 --> |Yes| de_to_publish
qa_notes_1 --> |No| promote_to_draft_2
promote_to_draft_2 --> create_child_2
create_child_2 --> close_child_2
close_child_2 --> and
```

**Comment by sf-dcp** [comment]
Discussion notes: 

- QA notes under child issue (may revise where to record them down the road).
- ideally use yellow "GIS" tag and assign GIS individually

**Comment by jackrosacker** [comment]
@NYCPlanning/gis team got to check in on this yesterday, and @croswell81 signed off, so all good to implement for either the next product builds, or for this second round of PLUTO QA, as you all prefer

**Comment by jackrosacker** [comment]
Sorry, ignore my deleted comment. This process is still in review on our end

**Comment by croswell81** [comment]
GIS Team reviewed this together and process makes sense. Let's implement this on the next DE product build.
cc: @jackrosacker @caseysmithpgh @damonmcc @fvankrieken @alexrichey @sf-dcp

**Comment by damonmcc** [comment]
@sf-dcp let's update our wiki, maybe the [Product Lifecycle](https://github.com/NYCPlanning/data-engineering/wiki/Product-Lifecycle) page?

**Comment by jackrosacker** [comment]
Niceee 
![image](https://github.com/user-attachments/assets/bba0dfd4-58c4-42f7-befd-d3c027500af0)
Appeared cleanly and automatically in our project workspace

**Comment by sf-dcp** [comment]
will close this issue after adding the new workflow process to our wiki

**Comment by sf-dcp** [comment]
[Here](https://github.com/NYCPlanning/data-engineering/wiki/Product-Lifecycle) is the updated page in our wiki, describing the process. Feel free to edit for more details/better formatting.
