### ISSUE TITLE
ZTL: qc_bbldiff.shp missing geometry

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/data-engineering#1052]
qc_bbldiff shapefile downloaded from [here](https://edm-publishing.nyc3.cdn.digitaloceanspaces.com/db-zoningtaxlots/draft/2024-08-01/1/qc_bbldiffs.shp.zip) appears to be missing geometry. The data opens in the attribute table of both Pro and QGIS, but displays no data on the map.

**Comment by fvankrieken** [comment]
So to complete this we should
- [ ] diagnose root cause
- [ ] correct code in dev branch (with a successful build) and merge to main
- [ ] rebuild on main
- [ ] promote new main build, with short informative revision text

**Comment by HengJiang0206** [comment]
@jackrosacker Hello Jack, I added the geometry column to `int_zoningtaxlots` and `qc_bbldiff` with #1055. Please let me know if there are other problems!

**Comment by jackrosacker** [comment]
Great! Thanks @HengJiang0206 - I'll take a look this afternoon. Confirming that this is the [file/location](https://edm-publishing.nyc3.cdn.digitaloceanspaces.com/db-zoningtaxlots/draft/2024-07-01/1/qc_bbldiffs.shp.zip) I should be pulling from?

**Comment by fvankrieken** [comment]
@jackrosacker - that's last month. The new draft is

db-zoningtaxlots/draft/2024-08-01/2-fix_qc_bbl_diffs

**Comment by fvankrieken** [comment]
This also includes my data fix that you and I talked about!

**Comment by HengJiang0206** [comment]
It's [here](https://edm-publishing.nyc3.cdn.digitaloceanspaces.com/db-zoningtaxlots/draft/2024-08-01/2-fix_qc_bbl_diffs/qc_bbldiffs.shp.zip)

**Comment by jackrosacker** [comment]
Perfect, the file in the 2024-08-01 location has geometry and loads fine in my GIS. Noting that the 2024-07-01 file is missing geometry. Doesn't matter for my QA, just a heads up.

Can we adjust the naming conventions of these folders to reflect how the GIS Team refers to data versions? i.e. July data should be in a 2024-07-31 folder, and so on.

**Comment by fvankrieken** [comment]
Not this second - needs to be part of a broader conversation. I'd love to try to align a bunch of versions this month

**Comment by jackrosacker** [comment]
Ok, sounds good. Would be great to address before next open data cycle so let's talk about it soon.
