### ISSUE TITLE
FacDB 24v2 QA - draft 1

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#1090]
FacDB page on QA app [here](https://de-qaqc.nycplanningdigital.com/?page=Facilities+DB)

**Comment by caseysmithpgh** [comment]
### FacDB 24v2 draft 1 GIS QA Results

#### Summary 
FacDB looked pretty good overall! Please review a few items in the table below to help better determine whether we need to rebuild. 

#### Results
Total record count: 
23v2:	34,171 
24v1:	35,305 (build 3) (published) 
24v2: 	35,008 

facsubgrps with notable changes: 
| facsubgrp | old | dif | pct abs dif | notes |
| --- | --- | --- | --- | --- |
| SUBSTANCE USE DISORDER TREATMENT PROGRAMS | 389 | -299 | 76.8% | factype changes: (OUTPATIENT CLINIC [-129]; OPIOID OUTPATIENT..[-47]; INTENSIVE RESIDENTIAL [-16]) |
| UNDEVELOPED | 54 | -18 | 33.3% | facdomain is parks gardens and historical sites. @croswell81 mentioned a loss in gardens recently, worth checking into |
| SOLID WASTE PROCESSING | 222 | -65 | 29.7 | **Source missing!**  factype: Scrap Metal Processing, source: dca_operatingbusinessess |

Additional Notes: 
- Jails and Courts both increased by +1, which was expected as it's sourced from COLP. 
- Seats and bed counts changed within reason
- No major changes in K-12 factypes

@damonmcc 
FYI @croswell81 @jackrosacker

**Comment by damonmcc** [comment]
[IN-PROGRESS]

## running notes on notable changes in 24v2 draft 1

- SUBSTANCE USE DISORDER TREATMENT PROGRAMS
  - the source dataset is `nysoasas_programs`
  - the version used (13-Aug-24) somehow had 1/10th of the rows in it and only had NYC counties (although I see no mechanism in our data library code that would've caused this)
  - I just archived the latest version (03-Oct-24) and it is similar in size to past versions (e.g. 16-Jan-24)
- UNDEVELOPED
  - ...

## conclusion

I should rebuild with new source data

**Comment by caseysmithpgh** [comment]
@damonmcc 

Makes sense, thanks for reviewing.  Good news we get to try out our new QA issue for every draft version approach for the first time!

**Comment by caseysmithpgh** [comment]
Closing. Draft 1 failed QA, Draft 2 build in progress.
