### ISSUE TITLE
ZTL - fix versioning, align s3 folder layout with other repos

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#11]
ZTL uses `%Y/%m/01` as date format for versioning, as written [here](https://github.com/NYCPlanning/data-engineering/blob/main/db-zoningtaxlots/bash/config.sh#L145) (if link is broken, changes have been merged and it's one of the only lines in the file). In s3 this creates unnecessary subfolders by month and day. This same version format is used in `EDM_DATA` for archives which get used in ztl build to generate qaqc outputs. I would propose
- [x] change version to `%Y-%m-01` to align a bit better with other products
- [x] add logic in interaction with `EDM_DATA` data to do something more postgres friendly than having dashes (maybe just remove dashes), both for writing and reading
- [x] update old exports in DO to use this format
- [ ] update historical `EDM_DATA` versions, both in table names and column values in the 3 qc tables
- [ ] make sure any downstream customers are fine. I think they would just get it from `latest` folder which doesn't have this issue

Beyond that, maybe worth going to the branch/date format we use for most repos, though maybe that can wait for another issue where we aim to align all data products, because many differ just barely (output/no output, whether latest is in main or one level above it, etc)

**Comment by athursland** [comment]
Looks like run instructions in the README for ZTL is outdated too - will update in PR for this issue

**Comment by damonmcc** [comment]
@fvankrieken @athursland

with Ali's PR https://github.com/NYCPlanning/data-engineering/pull/109 merged, do we wanna drop the tasks around changing old files and tables and close this?

**Comment by fvankrieken** [comment]
I think we should update s3 folders to align with this

**Comment by damonmcc** [comment]
renamed and moved all folders in `edm-publishing/db-zoningtaxlots` to have the pattern `YYYY-MM-01/output/...`
