### ISSUE TITLE
Opendata: Automate Zoning (6)

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#1124]

**Comment by alexrichey** [comment]
zoning_commercial_overlay_district: aaxv-7bvq
zoning_limited_height_districts: eh65-uhvn
zoning_special_purpose_districts: qs7n-2xb8
zoning_special_purpose_districts_subdistricts: 9ng7-qsbs
zoning_zoning_districts: frkw-si7h
zoning_zoning_map_amendments: k5u6-psh6

**Comment by croswell81** [comment]
I'll look at the draft pages by this afternoon

**Comment by alexrichey** [comment]
@croswell81 No hurry on this. Let's chat on Monday about how to work through reviewing all the new pages. I'll assemble a list of all the new Socrata pages in the meantime.

**Comment by croswell81** [comment]
[like]  Matthew Croswell (DCP) reacted to your message:
________________________________
From: Alex Richey ***@***.***>
Sent: Friday, September 13, 2024 4:35:40 PM
To: NYCPlanning/data-engineering ***@***.***>
Cc: Matthew Croswell (DCP) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NYCPlanning/data-engineering] Opendata: Automate Zoning (6) (Issue #1124)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.  Forward suspect email to ***@***.******@***.***> as an attachment (Click the More button, then forward as attachment).


@croswell81<https://github.com/croswell81> No hurry on this. Let's chat on Monday about how to work through reviewing all the new pages. I'll assemble a list of all the new Socrata pages in the meantime.

**Comment by alexrichey** [comment]
@croswell81 FYI, here are the new Zoning pages. I've double checked them, and also, now they'll have the OTI data dictionaries attached, which you should probably glance at. I'll make a comprehensive list on the excel sheet
