### ISSUE TITLE
Specify Shapefile Layer to Distribute to Socrata

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#1131]
Many products like DCM are packaged up into a shapefile with multiple layers. (each layer being a dataset on it's own)

- We can either figure out how to specify the layer to upload in the call to socrata itself. 
- Or delete the other layers from the zip. 
- Treat the shapefile as an assembly similar to a zipfile (I mean, technically it its) and "unpackage" it into a single shapefile. This might push us toward defining things at the product level, since this is a shapefile of the entire product.

**Comment by AmandaDoyle** [comment]
Not a useful enhancement with new Socrata data structure
