### ISSUE TITLE
Add manual research for 3014980035 lot information

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/data-engineering#115]
For 3014980035 
Update lot frontage from 67.25 ft to 120 and lot depth from 52.75 ft to 100 and lot area to 12,000 sq ft.
PTS is not in line with the DTM.

**Comment by fvankrieken** [comment]
Per @AmandaDoyle email:

> Good morning.  PTS has the lot frontage and lot depth as 67.25 ft and 52.75 ft respectively.  There is a precedent for DCP to update the lot area, but not the lot frontage and lot depth; however, given that PTS and the DTM do not align, I think it is appropriate to add manual corrections for the 3 fields for this lot.  Unfortunately, manual changes will not be reflected until the next major release.

Do we still need to update the area? Will include in 23v2.1 if so

**Comment by AmandaDoyle** [comment]
@fvankrieken 
The minor releases are really only supposed to have zoning changes, which is why I said this update would be reflected in the PLUTO23v3.  
As long as the lot area, depth, and frontage are not 12,000 sq ft, 100, and 120 we'll need to:
1) Add these records to the research file and
2) Add logic to be able to update lot frontage and lot depth, because I don't think this currently exists

**Comment by fvankrieken** [comment]
So what is needed is
- add one entry in `pluto_input_research.csv` for bbl 3014980035 for each lot area, lot depth, and lot frontage
- add logic to apply corrections for fields "lot depth" and "lot frontage", I would say in the file `corr_lotarea.sql`
