### ISSUE TITLE
PLUTO QAQC page: Fix Value Differences for Zoning table

### ISSUE THREAD

**Issue by sf-dcp** [NYCPlanning/data-engineering#1160]
Per GIS https://github.com/NYCPlanning/data-engineering/issues/976#issuecomment-2372401914, need to de-duplicate value differences for zoning: 

<img width="601" alt="image" src="https://github.com/user-attachments/assets/29caee8e-d4e8-4f7a-bdc8-274a22bea54a">

**Comment by damonmcc** [comment]
@sf-dcp good to close this? I think your PR didn't auto close it because it says `and #1160` instead of `fixes #1160`
