### ISSUE TITLE
write up framework for implementing this QA approach for other data products. Plan for future iterations

### ISSUE THREAD

**Issue by sf-dcp** [NYCPlanning/data-engineering#1183]
The goal of this write-up is to outline a process of creating data checks, using PLUTO as an example. This write-up will be also added to our wiki.

Also need to identify next steps post project. 

The write up will be added in the comments section. 

### Feedback requested: 
- feedback on testing framework guidelines 
- Q4 next steps plan

**Comment by sf-dcp** [comment]
# Testing Framework for Data Products

We’re simplifying the data engineering QA review process by incorporating domain experts' knowledge into binary checks. These checks make it easier to identify and resolve issues early in the build process, reducing the need for manual reviews. This process can be applied to any product, whether it uses `dbt` for builds or not. For products that aren’t using `dbt` yet, we can still add checks, and as we move towards using `dbt` for all products, these checks will continue to support the transition.

---

### Establishing a `dbt` Project for non-`dbt` Products

For products that don’t use `dbt` yet, we need to establish a `dbt` project within the product’s folder to create product-specific data checks. See PLUTO directory for reference.  

---

### When Should We Add a New Check?

If a product on average goes through 2+ manual draft reviews and distribution to consumers is behind product schedule, data checks should be added. For example, we should continue adding checks until we meet our goal of publishing PLUTO in a week. Priority should be given to checks addressing the most frequent data issues reported by GIS (or other team) QA reviews, especially those that Data Engineering (DE) has control over:

- DE needs support from domain experts to identify checks and define the logic behind them. In case of PLUTO, we need support from GIS or Amanda.
- We can draw inspiration from a current product QAQC streamlit page.
- These will be referred to as **DE checks**: if a check fails during the build, DE must resolve it before promoting to draft in `s3`.

---

### How to Request a New Check?

This section is based on PLUTO but can be applied to other products. 

To request a new check, either DE or GIS should create a GitHub issue outlining:

- The observed data quality issue.
- Examples of the data issue.
- The point of contact in GIS who can provide support to DE during check development.
- Add `pluto` and `qaqc` tags to the GH issue.
- Specify if it is a **DE check** or a **GIS check**.
    - **GIS checks** are typically requests for the QAQC page.
    - **DE checks** are binary pass/fail tests that must pass before PLUTO is promoted for GIS review.

---

### Process for Adding a New DE Check

After creating a GitHub issue:

1. **Gathering Information:**
   DE should gather details on the pass/fail conditions, the next steps in case of failure, and whether any outcome reports are needed. This step often involves collaboration with domain experts unless a check is simple.

2. **Implementing the Check:**
   DE will implement the check using the `dbt` framework:
   
   - **Singular vs. Generic Tests:** If custom logic is needed, implement it as a singular test under the `test/` directory. Otherwise, use dbt built-in tests and configure them in the appropriate YAML models file.
   
   - **Test Requirements:**
     - Provide a clear test description in the `config.meta` object.
     - Include next steps for DE in case of failure, also under the `config.meta` object.
     - Add the tag `de_check`. In case of PLUTO (or any other product with different version types), also add `major` and/or `minor` tag(s) to indicate which versions the test applies to.
     - If  a product can be promoted despite the test failure, set the error to a warning level in the test configuration. Otherwise, the default behavior will be to error out.
   
   - **Intermediate Tables:** If the test needs intermediate tables that are not in the database build schema, create them under `models/qaqc/intermediate/`.
   
   - **Report Models:** If a report is needed as part of the product output files, create the report model under `models/qaqc/reports/`.

---

### Difference Between Tests at Ingest vs. Build

- **Source Tests:** These are expected to focus on schema (columns) and validation only.
  
The line between ingest and build tests can be blurry, but it’s often better to have more tests. We can always remove duplicates later if the same test exists in both stages.

---

### Next Steps for PLUTO QAQC (Q4)

1. **Continue Adding Checks:** 
   We can continue adding checks that apply to source and product tables because:
   - Most data quality issues stem from source data.
   - It doesn’t conflict with or hinder the refactoring of PLUTO in dbt.
   - 

2. **Potential Future Checks:**
   We need to identify additional data checks—support in this area is appreciated.

3. **PLUTO Refactor in dbt:** 
   Start refactoring PLUTO using dbt to align with these new testing processes.

4. **Dashboard Creation:** 
   Once we have a minimum of 10? checks or start adding a testing framework to other products, we can create a dashboard to track them.

---

### Feedback Needed

- Ongoing collaboration with GIS to identify more checks—possibly with recurring meetings to review and research.
- How to approach refactoring PLUTO, and when can we begin? My personal preference is to start as soon as possible.

**Comment by AmandaDoyle** [comment]
WIP - posting so I don't lose what I wrote so far
Below are my ideas for DE QA checks to improve the PLUTO review process.

PLUTO minor:
- Check that the number of records is the same as the previous version; we should not be adding or subtracting records
- Check that no fields have had a change in value except for the following:
                    ZoneDist1 		SPDist1		    	   CommFAR 
                    ZoneDist2 		SPDist2		    	   FacilFAR 
                    ZoneDist3 		SPDist3		       	   ZoneMap 
                    ZoneDist4 		LtdHeight		ZMCode 
                    Overlay1 		SplitZone		TaxMap 
                    Overlay2		ResidFAR		EDesigNum

**Comment by alexrichey** [comment]
@sf-dcp This looks great. Thanks for writing it up. My only feedback is about when "When Should We Add a New Check?" - I'm not sure it's helpful to have such specific rules about number of draft reviews. Ideally we write a new test whenever we identify that it would save potentially significant time in the future, which could include cases where there was only a single (successful) draft review, but where some investigation was needed by either DE or GIS. So I think we can use our discretion here.

Somewhat out of scope, but in terms of process, maybe it would be also worthwhile to do an analysis with GIS and Amanda of the release timeline whenever we fail to deliver a product on time. I think that might yield some very good DE Checks. The industry term for these is "post-mortems", but it's something we haven't really done.

**Comment by damonmcc** [comment]
@sf-dcp thanks for such a thorough write-up. in addition to agreeing with @alexrichey feedback, a couple of thoughts:
- should we drop the term QAQC and just always say QA? I think we discussed in a roadmapping a while back and felt like QA was enough
- we could probably try making a DE Check Dashboard once we have checks for more than one dataset. 10 checks is a good minimum but it feels like the more significant factor is designing it with more than one product in mind

to reply to ur explicit callouts:

1. Continue Adding Checks:
🚨 ACTION/FEEDBACK needed🚨: identify next data checks — support from Amanda or GIS
- looks like Amanda listed two checks for PLUTO minor we can do next
- maybe let's find a valuable check to do for a non-PLUTO dataset that we build frequently
🚨ACTION/FEEDBACK needed🚨: establish collaboration expectations with GIS — possibly with recurring meetings to review and research
- seems like we might want two recurring meeting with GIS: bi-weekly to review data updates, less frequently (quarterly?) to review and research checks

2. PLUTO Refactor in dbt:
🚨ACTION/FEEDBACK needed🚨: how to approach refactoring PLUTO and when (my personal preference is asap)
- PLUTO's got a lotta sql. if the refactoring would be all-or-nothing, I'd vote we wait and add more checks first. if the refactoring would be gradual (e.g. convert the last tables first), I don't see why we couldn't start this soon

**Comment by sf-dcp** [comment]
@alexrichey @damonmcc Thanks for the feedback! All great points.

* @damonmcc, yes, def lets drop the QC part :) For PLUTO refactoring... Maybe we could start with untangling current PLUTO pipeline into an acyclic graph, write some basic tests for the new intermediate tables, and then start refactoring in dbt from the end? 
* @alexrichey, agree with using our own discretion for writing checks. My thought behind using a draft count  is for identifying which products should be prioritized for data tests and just having a proactive approach towards developing checks. 
* I also googled "post-mortems" term... on its own... and oh boy. Should have added "data engineering" in the end :) I'm really curious about implementing something like this, so let's chat! It seems very relevant to us.

**Comment by damonmcc** [comment]
@sf-dcp, noting this for future iterations, not as an expectation of this project

@AmandaDoyle suggested FacDB as a good data product to make DE checks for:
- high impact data product
- lengthy QA lacking binary checks
- built twice a year

**Comment by AmandaDoyle** [comment]
Ideas for PLUTO major QA checks to reduce the amount of time it takes to move PLUTO from build to publication:
1) What I heard many times was how do we know what is expected change when reviewing the "mismatch graphs" or "percent change in sum" on the QAQC page?  Therefore, for the benefit your future selves and future DE and GIS team members, I encourage you to start to quantify what "normal" change is.  For example, what the average number of records that experience a "comarea" change between PLUTO major releases.  If during a build the number of records that change fall outside of the standard deviation perhaps that should set off some yellow flags where research may need to be done to validate changes or correct issues.
2) Verify the number of records changed.  The number of records should always change as part of a PLUTO major release.  If the numbe of records don't change this should be a red flag.
More to come.

I proposed that Facilities Database be the second dataset to undergo QA scrutiny because of the lengthy QA process that lacks binary checks and because there is a lot of opportunity to add QA checks to both input datasets and output tables.
Checks for output tables (WIP):
1) Check that the number of records with the following factypes did not change.  If so, the changes will need to be investigated:
- Senior center
- Special library 
- Police station
- Nursing home
- Hospital
- Firehouse
- Academic libraries
- Adult day care

**Comment by sf-dcp** [comment]
@AmandaDoyle GIS also suggested a check for 2020 census tracts not changing between versions. Would need more info

**Comment by sf-dcp** [comment]
From chat w/Amanda, next steps for Q4 (outside of this project):

* This write-up looks good
* We will be meeting every X weeks to discuss data checks
* Add data check for pluto minor where only certain selected fields are expected to change
* Add data check for pluto major where record count should change from version to version
* 2020 census track check: census tract may change when lots gets merged/divided. Need to investigate lots with changed tracts in upcoming PLUTO 24v4 and decide whether we will be adding a check
* We would like to create new QAQC visuals for historical change with a "normality" indicator (can't think of a better word). We will start with area fields coming from CAMA dataset. I will spend Q4 brainstorming infrastructure for such reports.
*  Maybe we could also add a check for freshness for certain datasets. One example is zoning data
