### ISSUE TITLE
GFT 24v3 Draft 2 QA

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#1199]
Find outputs [here](https://cloud.digitalocean.com/spaces/edm-publishing?i=266877&path=db-green-fast-track%2Fdraft%2F24v3%2F2-fix_sources_with_null_geoms%2F)

**Comment by jackrosacker** [comment]
GFT 24v3 Draft 2 QA has **passed**!
I didn't cover all criteria listed in [my comment on the Build/Draft 1 issue](https://github.com/NYCPlanning/data-engineering/issues/1004#issuecomment-2414882194), as many of them are not feasible to do manually, but all issues we'd found in Draft 1 have been resolved. Thanks @fvankrieken! Please promote at your convenience. I will use the same data I pulled locally for QA to publish to the app.

cc: @NYCPlanning/gis

**Comment by fvankrieken** [comment]
Published!
