### ISSUE TITLE
bug when extracting `dcp_lion`

### ISSUE THREAD

**Issue by sf-dcp** [NYCPlanning/data-engineering#1256]
Encountered an issue when extracting 24d lion [here](https://github.com/NYCPlanning/data-engineering/actions/runs/11921514693/job/33226971270). 24d version is present on Bytes.

**Comment by fvankrieken** [comment]
There's actually an issue for this - #600 

In the past, I've run locally and specified pg_dump as output format. I had hoped that we'd be on ingest by now and that this wouldn't be an issue at this point, sorry! 😬

**Comment by sf-dcp** [comment]
Oops! Will close this issue. I actually don't need lion for PLUTO, it was a part of other dcp datasets I was extracting in batch.
