### ISSUE TITLE
Failed action: Zoning Tax lots - 📁 DataLoading

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/data-engineering#1297]
[Run history here](https://github.com/NYCPlanning/data-engineering/actions/runs/12127713617)

**Comment by damonmcc** [comment]
@fvankrieken maybe this is from migrating from library to ingest and deleting the old templates?

**Comment by fvankrieken** [comment]
Ah shoot. Will fix shortly

**Comment by fvankrieken** [comment]
Dataloading has passed on my dev branch [here](https://github.com/NYCPlanning/data-engineering/actions/runs/12142003482)

@jackrosacker all set, ztl should be built soon. No need for you to re-run anything

**Comment by fvankrieken** [comment]
`2024-12-01` built and promoted to draft
