### ISSUE TITLE
Pluto 24v4 QA - Draft 2

### ISSUE THREAD

**Issue by sf-dcp** [NYCPlanning/data-engineering#1324]
QAQC [page](https://de-qaqc.nycplanningdigital.com/?page=PLUTO).

DO [link](https://cloud.digitalocean.com/spaces/edm-publishing?path=db-pluto%2Fdraft%2F24v4%2F2-manually-correct-res-units%2F).

**Comment by sf-dcp** [comment]
hurray! 🍾

**Comment by caseysmithpgh** [comment]
@sf-dcp 
Just let me know once it has been promoted to published :)

**Comment by sf-dcp** [comment]
Yep, on it! @caseysmithpgh
