### ISSUE TITLE
ZAP project-bbl record count anomaly 

### ISSUE THREAD

**Issue by caseysmithpgh** [NYCPlanning/data-engineering#152]
Over a million records are included in the zapprojectbbl.csv output from June 6th, 2023 as well as July 3, 2023. This is a **significant** record count increase from previous opendata cycles (5/8/23 version had 66,869 records). 

GIS suspects this likely is a filtering issue that is leading to internal records being included in the final outputs. 

@damonmcc @AmandaDoyle @fvankrieken

**Comment by damonmcc** [comment]
record counts for most recent run in monorepo:
- `dcp_projects`: 64,852
- `dcp_projectbbls`: 538,280

all records in `dcp_projects` have a `dcp_visibility` value of `General Public`, so this doesn't seem to be an issue with removing non-public ZAP records

**Comment by caseysmithpgh** [comment]
@damonmcc does this mean the latest outputs are clean or should GIS wait for further changes? 

fyi @jackrosacker

**Comment by damonmcc** [comment]
@caseysmithpgh

these still seem like really big increases in records so I'm hesitant to say they're good to go. I'll look into duplication and cross-joins as potential causes of the issue and report back ASAP

these outputs are all still going to `edm-publishing` so if they do look good to GIS, they look good to me!

**Comment by damonmcc** [comment]
@caseysmithpgh 

I'm seeing lots of duplicative records in the raw Project BBL data. and since we do two inner joins using those records and the project-records (probably one join too many), I imagine duplicates would cause an erroneous increase in final records

I'll make sure we remove duplicates and that our joins aren't also part of the problem

**Comment by damonmcc** [comment]
@caseysmithpgh I think we're good to go!

I'll check row counts and update this comment but the file sizes from the 8/15 build are very close to those from 7/17
