### ISSUE TITLE
db-factfinder variables missing from decennial metadata files

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/data-engineering#179]
# Description
Please add the following variables to the `decennial/2020/[version]/metadata.json`.

Spouse, OpSxS, SmSxS, UMrdPtnr, OpSxUMrd, SmSxUMrd, Child, ChildU18, GrndCh, GrndChU18, OthrRel, NonRel, Fam, NFamHH, NFmHHU65, MrdCplHH, MrdCh18, CoCplHH, CoCplCh18, MaleHHNS, MnSPChU18, FemHHNS, FnSPChU18

## Context
~~These variables appear for 2020 but not 2010. There was a brief discussion on strategies other than adding the variables to a single metadata file for each data source. However, the ACS data already has instances where variables in one year are not found in another year. Consequently, the ingest pipeline for labs-factfinder-api is already designed to handle variables that occur in one year and not another. This is likely something we will want to reconsider in future iterations of the pipeline. But for the immediate data needs, I would prefer to keep the current file structure.~~

Removed the context because it was based on faulty assumptions and was adding confusion.

**Comment by fvankrieken** [comment]
So just to make completely clear - these variables are currently present in the metadata files for 2020 (in relevant s3 folder), but what you'd prefer the same "complete" metadata file exported for both year versions

**Comment by TangoYankee** [comment]
> So just to make completely clear - these variables are currently present in the metadata files for 2020 (in relevant s3 folder), but what you'd prefer the same "complete" metadata file exported for both year versions

Negative chomp. These variables are missing from the metadata file for decennial data (version 2023-08-21). I am requesting they be added to the metadata.json.
