### ISSUE TITLE
Pluto Proxcode discrepancies

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#199]
In the course of QA'ing changes for automated Pluto Minor builds, we encountered an issue with Condo `proxcode`s were changing between two builds that _should_ have generated identical outputs.  This only applied to condo units.

e.g. for `billing bbl` = 5051907501, a [condo unit](https://zola.planning.nyc.gov/l/lot/5/5190/7501?aerial-year=aerials-2016&layer-groups=%5B%22building-footprints%22%2C%22commercial-overlays%22%2C%22street-centerlines%22%2C%22subway%22%2C%22tax-lots%22%2C%22zoning-districts%22%5D&print=false&search=true&selectedCouncilDistricts=%5B%222013%22%5D&selectedFirm=%5B%22A%22%2C%22Shaded%20X%22%2C%22V%22%5D&selectedOverlays=%5B%22C1-1%22%2C%22C1-2%22%2C%22C1-3%22%2C%22C1-4%22%2C%22C1-5%22%2C%22C2-1%22%2C%22C2-2%22%2C%22C2-3%22%2C%22C2-4%22%2C%22C2-5%22%5D&selectedPfirm=%5B%22A%22%2C%22Shaded%20X%22%2C%22V%22%5D&selectedZoning=%5B%22BP%22%2C%22C1%22%2C%22C2%22%2C%22C3%22%2C%22C4%22%2C%22C5%22%2C%22C6%22%2C%22C7%22%2C%22C8%22%2C%22M1%22%2C%22M2%22%2C%22M3%22%2C%22PA%22%2C%22R1%22%2C%22R10%22%2C%22R2%22%2C%22R3%22%2C%22R4%22%2C%22R5%22%2C%22R6%22%2C%22R7%22%2C%22R8%22%2C%22R9%22%5D&shouldRefresh=false#15.49/40.547025/-74.13275) on Staten Island. 

There are 53 units, e.g. `5051901001`, `5051901002`, `5051901003`... with varying proximities to other buildings. When Pluto collapses the condo bbls to  a single bbl, the choice of proxcode wasn't deterministic. 

Proposed solution [here](https://github.com/NYCPlanning/data-engineering/pull/198). Will review when @AmandaDoyle returns from PTO

**Comment by AmandaDoyle** [comment]
@alexrichey I approve of this change.  I'm flagging that we'll need to update the ProxCode definition in the [data dictionary](https://s-media.nyc.gov/agencies/dcp/assets/files/pdf/data-tools/bytes/pluto_datadictionary.pdf) to reflect this change.
