### ISSUE TITLE
KPDB runs out of space during SCA aggregation

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#206]
see [this error](https://github.com/NYCPlanning/data-engineering/actions/runs/6104970649/job/16567771715#step:7:30) during a build

this error is more descriptive when using a DB created by the github action. when using `edm-data`, the error is something like "connection terminated by administrator"

**Comment by fvankrieken** [comment]
Ooh - this seems like it could be actually storage and just not memory, edm-data is at 92% right now. Should we potentially clear anything out?

**Comment by fvankrieken** [comment]
At least for in the gha - I wouldn't be surprised if DO databases have some sort of safeguard to kill a connection when storage limit is about to be reached?

**Comment by fvankrieken** [comment]
Might also be time to just bump the overall storage if we're committed to using it as a build engine across products. Though that being said currently we're really not using most of the stuff in there and I'm not sure how useful any of it is to us

**Comment by damonmcc** [comment]
closing since it seems to be fixed by ensuring there's enough free storage in edm-data DB (<80% Data Usage)

optimizing the sql queries would be a significant enhancement
