### ISSUE TITLE
dcpy.recipes - Replace Cerberus with Pydantic

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#223]
[Here](https://github.com/NYCPlanning/data-engineering/blob/678e70582e4571307c2924fbd99b36274a9deac6/dcpy/connectors/edm/recipes.py#L28)

Cerberus was a quick way to schematize things, but Pydantic would give us a concrete class (and would be in line with how we do things in `data-library`). We should swap the schema and implementation. 

cc @fvankrieken + @damonmcc + (Sasha, once she's set up)

**Comment by damonmcc** [comment]
@alexrichey done I think? although looks like we didn't remove cerberus from requirements.in

**Comment by alexrichey** [comment]
@damonmcc Good catch! And yes, closing this (will add a PR for Cerberus)
