### ISSUE TITLE
PLUTO build version: 23v3

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#241]
## Code updates:

- [x] Update version in [recipe.yml](https://github.com/NYCPlanning/data-engineering/blob/main/products/pluto/recipe.yml)

#### Updated 2x a year typically in June and December
- [x] **dcp_colp** (check [here](https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-colp.page)) 
#### Currently updated with each new release of a major version of PLUTO - important to make sure this is up to date
- [x] **pluto_corrections** (pulling from bytes, must update when there's updates to **pluto_input_research**)

#### Open data automated pull

> Check [here](https://github.com/NYCPlanning/db-data-library/actions/workflows/open-data.yml) to see the latest run

- [x] **dsny_frequencies**
- [x] **dpr_greenthumb**
- [x] **lpc_historic_districts**
- [x] **lpc_landmarks**

#### DOF Automated Pull and Number of Buildings

- [x] **pluto_pts** (Check [here](https://github.com/NYCPlanning/data-engineering/actions/workflows/pluto_input_pts.yml))
- [x] **pluto_input_geocodes** (Check [here](https://github.com/NYCPlanning/data-engineering/actions/workflows/pluto_input_pts.yml))
- [x] **pluto_input_cama_dof** (Check [here](https://github.com/NYCPlanning/data-engineering/actions/workflows/pluto_input_cama.yml))
- [x] **pluto_input_numbldgs** (Check [here](https://github.com/NYCPlanning/data-engineering/actions/workflows/pluto_input_numbldgs.yml))

### Updated with Quarterly updates (check [here](https://github.com/NYCPlanning/db-data-library/actions/workflows/quaterly-updates.yml))

- [x] **dcp_cdboundaries_wi**
- [x] **dcp_ct2010**
- [x] **dcp_cb2010**
- [x] **dcp_ct2020**
- [x] **dcp_cb2020**
- [x] **dcp_school_districts**  
- [x] **dcp_councildistricts_wi**  
- [x] **dcp_firecompanies**  
- [x] **dcp_policeprecincts**
- [x] **dcp_healthareas**  
- [x] **dcp_healthcenters**

### Updated with Zoning Taxlots 

(check [here](https://github.com/NYCPlanning/db-zoningtaxlots/actions) for latest run).

These are all produced by GIS, who typically update them sometime in the first week of each month.
Check in with them before archiving with data library

- [x] **dof_dtm**
- [x] **dof_shoreline**
- [x] **dof_condo**
- [x] **dcp_commercialoverlay**
- [x] **dcp_limitedheight**
- [x] **dcp_zoningdistricts**
- [x] **dcp_specialpurpose**
- [x] **dcp_specialpurposesubdistricts**
- [x] **dcp_zoningmapamendments**
- [x] **dcp_edesignation**

### Never Updated (Safe to ignore)

- [x] **doitt_zipcodeboundaries** (almost never updated, check [here](https://data.cityofnewyork.us/Business/Zip-Code-Boundaries/i8iw-xf4u))
- [x] **fema_firms2007_100yr**
- [x] **fema_pfirms2015_100yr**
- [x] **dcp_zoningmapindex**

# Build CI Runs

- **[INSERT LINKS TO RELEVANT CI RUNS HERE]**
 
# Comments

**Comment by fvankrieken** [comment]
@AmandaDoyle - pluto_inputs_cama hasn't been updated since March, which is an uncharacteristic gap - we had that period this summer where those data loading steps were broken. Do you think it's possible we "missed" an update? Those files seem to only be on the ftp server relatively briefly

**Comment by fvankrieken** [comment]
Needs #115

**Comment by AmandaDoyle** [comment]
@fvankrieken I don't think we missed an update.  I reached out to DOF requesting a new file (you're cc'd)

How is #115 related?

Thanks!

**Comment by fvankrieken** [comment]
It's needed as a part of this major update, no?

**Comment by AmandaDoyle** [comment]
Ah yes.  Sorry.  Yes, the correction should be made as part of the major updates.  If you and the team need any help doing that I'm happy to show you how.

**Comment by fvankrieken** [comment]
@sf-dcp - go ahead and continue through this checklist, and once things are done (including making a new branch to make the one code change at the top of the list), kick off a build per [Pluto's README](https://github.com/NYCPlanning/data-engineering/tree/main/products/pluto)

**Comment by sf-dcp** [comment]
@AmandaDoyle, what is the actual schedule for Bytes quarterly updates?

**Comment by damonmcc** [comment]
awaiting new zoning data from GIS

**Comment by sf-dcp** [comment]
Status update: GIS has been tagged for a review.
