### ISSUE TITLE
ZTL issues arising from duplicate BBLs in DTM

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#278]
Per discussion with @caseysmithpgh and @jackrosacker 

New logic in #171 updated some rankings of zoning districts by bbl based on aggregation. There are a couple odd edge cases where it seems there are multiple entries for bbls in dtm. Due to the way the aggregation/ranking of zoning districts logic is written, we're getting (extra) duplicate rows for bbls as well as duplicate rankings.

So if bbl 1 appears twice and should be zd1 = R5 and zd2 = Park (zd3, zd4 both empty), what we're seeing is 
| bbl | zd1 | zd2 | zd3 | zd4 | 
| - | - | - | - | - |
| 1 | R5 | R5 | Park | Park |
| 1 | R5 | R5 | Park | Park |
| 1 | R5 | R5 | Park | Park |
| 1 | R5 | R5 | Park | Park |

We **don't** want to remove the duplicate bbls, since that's coming from dtm. However, we do want to remove the extra rows and duplicated zoning districts

Other random notes
- 2050340001 has second district that doesn't seem to be above threshold
- 2028650160

**Comment by fvankrieken** [comment]
So we actually __do__ remove duplicates in dtm, with the following query

```sql
    SELECT
        bbl,
        COALESCE(boro::text, LEFT(bbl::text, 1)) AS boro,
        COALESCE(block::text, SUBSTRING(bbl::text, 2, 5)) AS block,
        COALESCE(lot::text, SUBSTRING(bbl::text, 7, 4)) AS lot,
        ST_MULTI(ST_UNION(ST_MAKEVALID(f.geom))) AS geom
    FROM dof_dtm AS f
    GROUP BY bbl, boro, block, lot
```
The issue here is that we have some of these "duplicates" where they have same bbl but different borough, block, or lot. Specifically lot

![image](https://github.com/NYCPlanning/data-engineering/assets/9454672/fef5365a-7a02-44bd-a403-951445c17fb4)

I think the fix is implemented, we can check the outputs tomorrow. But just given the specific example of this behavior, I wanted to raise the question on if we want to re-evaluate how we're grouping the dtm. @AmandaDoyle ?

**Comment by AmandaDoyle** [comment]
Oh my.  How is what looks like it would be 4159050303 becoming 415905003 (or vice versa)?  We do need to group the dtm, but if the current way is causing unexpected issues, let's revaluate.  Maybe it's only grouping by BBL?

**Comment by fvankrieken** [comment]
So per what we discussed earlier, it'd potentially be desirable to leave the current grouping, but just make sure that code runs smoothly (zoning district assignment doesn't get messed up by duplicate bbls, which is what @caseysmithpgh saw originally).

To actually address the root issue in dtm, if that's what we want to do, we could either 
- group by only bbl, derive boro block and lot from bbl. However this throws away the data we have that differentiates these two rows. If they refer to different footprints, they'd just get unioned
- have some sort of special logic if bbl and provided boro, block, and lot don't match up. Override bbl with boro+block+lot if they're provided? But obviously, does the opposite a bit

If any of those fields being off is really a dtm issue that we don't want to be overly specific about trying to correct, then we can just do neither and report issues like this
