### ISSUE TITLE
low `dcpy` test coverage

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#282]
from [recent tests on main branch](https://github.com/NYCPlanning/data-engineering/actions/runs/6462904706/job/17545247537#step:4:41), `dcpy` is at 11% test coverage

increasing this by any amount would be valuable, especially for the most commonly used `dcpy` modules

## goals
- write tests to cover a single `utils` function
- write tests to cover a single `connectors` function

## proposed approach
- choose a function and write enough tests to ensure no lines of that function are missed in the dcpy pytest coverage report

## notes
- a function could be considered "covered" by tests if no lines of it are missed in the coverage report ([report example](https://github.com/NYCPlanning/data-engineering/actions/runs/6498068240/job/17648610618#step:4:41))

**Comment by alexrichey** [comment]
@damonmcc @sf-dcp @fvankrieken Before we embark on any solutioning or implementation, can we formulate this as a problem statement? Ie can we clarify what problem we intend to solve here? Perhaps issues we've encountered, or expect to encounter.

**Comment by fvankrieken** [comment]
I think a more specific case would be adding testing for connectors.publishing and recipes - these are abstracted functions which very much could see the underlying functionality change at some point at which point it would be good to have automated unit tests. We/I have changed the functionality of these a fair amount already, and I have broken it in a way that would have been caught by a test

I do also think some of the slightly more involved s3 utils (upload folder, copy folder - each of which loops through objects and call other s3 utils) would be good to have tests. Both I could see us, for example, working on performance and refactoring slightly, in which case tests would be useful. Ones like download_file or upload_file I'm not concerned about

**Comment by fvankrieken** [comment]
> I think a more specific case would be adding testing for connectors.publishing and recipes - these are abstracted functions which very much could see the underlying functionality change at some point at which point it would be good to have automated unit tests. We/I have changed the functionality of these a fair amount already, and I have broken it in a way that would have been caught by a test
> 
> I do also think some of the slightly more involved s3 utils (upload folder, copy folder - each of which loops through objects and call other s3 utils) would be good to have tests. Both I could see us, for example, working on performance and refactoring slightly, in which case tests would be useful. Ones like download_file or upload_file I'm not concerned about

Counterpoint to the publishing and recipes - if the underlying functionality changes too much, we might need to write new tests anyways? But maybe if we write t

**Comment by sf-dcp** [comment]
After reviewing existing tests in the repo, I see an opportunity to add tests for `dcpy` functions that interact with S3. As we discussed, we probably don't want to write tests interacting with our production S3 bucket but instead use something to mock the behavior. 

From my search online, [moto](http://docs.getmoto.org/en/latest/docs/getting_started.html#decorator) seems to be good solution for mocking `boto` calls, and it's supposed to work well with `pytest`. The use of `moto` requires defining AWS dummy credentials and instantiating an s3 client (or any other boto client) with `moto` decorator or context manager.

I encountered an issue when using our function that instantiates `client()` from `utils/s3.py`. The client takes in AWS credentials that are extracted from env variables. I added a pytest fixture setting up AWS env variables to "testing", hoping `client()` would use them when instantiated. However, it would use the AWS env values that exist outside of testing. If we want to use our defined client for AWS mock calls, it seems that we want to do either: 

1) set up a different scope for pytest fixture (currently it says "function"), or;
2) wrap a call to client with `moto` decorator or context manager. 

### My next steps
* Write a test for `list_objects()` function in `utils/s3.py`. 
* Write tests for `connectors/edm/` module. TBD on which tests to write.

**Comment by fvankrieken** [comment]
Per discussion today with @sf-dcp , proposed testing for connectors.edm.publishing

Really, goal is to test main functionality of `upload` and `publish` to make sure that when refactors occur, data is still being put where it's supposed to be. Testing successfully running these functions will inherently require testing of the publishing utilities around reading metadata and data, so we'll cover a decent portion of the file.

Workflow within the pytest file would look something like this
- declare literals (either quite literally literals, or fixture)
  - bucket
  - product name
  - build environment (for DraftKey)
  - version (for version.txt and PublishKey)
- generate dummy data (fixture/helper function)
  - create an output folder in local filesystem (or used some sort of tempfile solution)
  - add both `version.txt` with generated version and some sort of dummy csv
- assert no draft versions or publish versions of our product (`get_published_versions` and `get_draft_builds` - sanity check/make sure we aren't using artifacts from prior tests or actual data) 
- test upload
  - run upload for our draft key and output folder
  - assert draft version found 
  - assert `get_version` returns appropriate version
- test publish
  - run publish for our draft key - do delete the draft, do not explicitly specify version
  - check draft builds (should be none)
  - check published versions (should be this build and latest)
  - read_csv, verify data
