### ISSUE TITLE
Zoning District Tileset

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/data-engineering#284]

**Comment by TangoYankee** [comment]
# Zoning District Tileset
The zoning district tileset will have the structure shown below.

![structure drawio](https://github.com/NYCPlanning/data-engineering/assets/11068062/eca2afeb-f536-4dfa-a731-2579267cd668)


## Cleaning

### Filters
Rows should be removed when their `zonedist` field is one of these values  
- PARK
- BALL FIELD
- PUBLIC PLACE
- PLAYGROUND
- BPC
- `null`
- an empty string

## District classifications from zoning code

A single district may contain multiple types of zoning classifications. For example, an M1/R6A district contains both a manufacturing and a residential classification. The “commercial”, “manufacturing”, and “residential” fields represent which zoning code of each zoning classification is found in the district. If no zoning code is present, the field is null. In our example, “manufacturing” would be ‘M1’, “residential” would be ‘R6’, and “commercial” would be null.

**Note:** The zoning code is limited to the classification letter and the code number, such as ‘R6’. Any trailing symbols are ignored, such as the ‘A’ in R6A.

## Examples

The charts below demonstrate how a zoning code may be processed into separate classifications

| Starting zonedist | Split into list, separating on '/' | Trim each to first letter and number | Assign to category            | 
|-------------------|------------------------------------|--------------------------------------|-------------------------------|
| C3A                     | [C3A]                                             | [C3]                                                 |  ![example-1-results drawio](https://github.com/NYCPlanning/data-engineering/assets/11068062/cb0729c4-9653-4ace-9d9d-8519c72b4d73) |
| M1-1/R7-2         | [M1-1,R7-2]                        | [M1,R7]                              | ![example-2-results drawio](https://github.com/NYCPlanning/data-engineering/assets/11068062/fb01384d-1a39-44c9-915b-9fc48406f0bb) |
| R10               | [R10]                              | [R10]              |  ![example-3-results drawio](https://github.com/NYCPlanning/data-engineering/assets/11068062/0aba4a42-f9c8-4f2e-be96-6023da1408ce) |

**Comment by TangoYankee** [comment]
The label should also be placed according to the [pole of inaccessibility](https://en.wikipedia.org/wiki/Pole_of_inaccessibility) using the polylabel [package](https://github.com/mapbox/polylabel) / [algorithm](https://blog.mapbox.com/a-new-algorithm-for-finding-a-visual-center-of-a-polygon-7c77e6492fbc)

This assumes that each area with a certain zoning classification has its own polygon that can be given its own label. If the data is organized into a single multipolygon representing all areas that have the same zoning classification, then that multipolygon would likely need to be split into individual polygons.

**Comment by TangoYankee** [comment]
If there are complications in creating the label features, then we would prefer to have the fill features delivered without the labels rather than waiting for the labels and fills to be delivered together.

**Comment by TangoYankee** [comment]
From a discussion with @fvankrieken, [ST_MaximumInscribedCircle](https://postgis.net/docs/manual-3.3/ST_MaximumInscribedCircle.html) provides similar results as polylabel, but is already built into PostGIS and supports multipolygons.

**Comment by fvankrieken** [comment]
The district column of the fill feature - that's just the initial district, right? As in, "M1-1/R7-2"

**Comment by TangoYankee** [comment]
> The district column of the fill feature - that's just the initial district, right? As in, "M1-1/R7-2"

correct

**Comment by fvankrieken** [comment]
One other question - it seems that there's no unique id linking fill and label. Is that fine? Happy to generate an id before the data is split into the two features

**Comment by TangoYankee** [comment]
> One other question - it seems that there's no unique id linking fill and label. Is that fine? Happy to generate an id before the data is split into the two features

I think we will want to have an id- not only to link the features within the tileset but also the tileset to the Zoning district table in the dataset. In #302, we indicate the zoning district id should be a uuid. I think we want that id to be the same across the database rows and the tileset features.

@TylerMatteo, if you agree then I'll update the diagram

**Comment by TylerMatteo** [comment]
@TangoYankee @fvankrieken Yeah let's try to include those UUIDs in the tiled data as well.

**Comment by TylerMatteo** [comment]
@fvankrieken The ideal min/max zoom for this is 9-22.

**Comment by TylerMatteo** [comment]
@fvankrieken Just adding a papertrail for our IRL discussion - I believe the error I'm getting when trying to use the tiles is due to the tiles being compressed (See "COMPRESS" flag in [GDAL MVT driver docs](https://gdal.org/drivers/vector/mvt.html#dataset-creation-options)). Hopefully fixing is as simple as passing `-dsco COMPRESS=NO` flag to GDAL.

**Comment by fvankrieken** [comment]
Closing for now with merging of code completed so far.

Tracking this and related issues in a milestone now, with one remaining open ticket for optimization of tileset generation. Feel free to open up follow-up tickets and put the appropriate milestone
