### ISSUE TITLE
Pull Requests Trigger Too Many Workflows

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#286]
Opening a PR with `dcpy` changes causes about 15 workflows to run (see [here](https://github.com/NYCPlanning/data-engineering/actions/runs/6470296936/job/17566195996?pr=283) for an example build). This may not be a problem at the moment since jobs run concurrently, but I could see this getting out of control, especially as we expand test coverage / linting / etc. 

I think there's certainly value in triggering product tests whenever we modify `dcpy`, however there may be alternate ways to ensure that changes to `dcpy` don't break our products. For example, now that we pip install `dcpy`, we could pin products to a certain version (a commit hash, or a tag/release) of `dcpy`. (this isn't necessarily a suggestion - it's more to prompt us to get creative)

Opening an issue as a place to discuss. It may be that there's no real problem here, especially if we're not paying for the compute time.

ping @sf-dcp @damonmcc @fvankrieken

**Comment by fvankrieken** [comment]
The main thing for me is static type-checking - if we change things in dcpy, I want everything that references it have mypy run. Currently we have mypy in each of the product/app-specific test workflows, we could just move the mypy step to the main workflow. 

Building/integration we should probably just make less sensetive - not run on dcpy, python req changes.

I do worry about the case where we bump some python packages and something specific to one repo breaks, but maybe that's a rare enough case that we should just address it if it arises and not make things hard for ourselves to prevent a very unlikely problem

**Comment by alexrichey** [comment]
@fvankrieken I agree. I feel like there are other approaches that are more complicated than just running mypy on everything. Maybe down the road we explore caching the `.mypy/` output. In the meantime, we should probably work on having just a single run of `mypy` since each check seems to cover `dcpy`.

**Comment by alexrichey** [comment]
also, @fvankrieken / @damonmcc / @sf-dcp curious if you think there's an acceptable threshhold for test times. Ie. is it acceptable for all the tests to take, say, 10 minutes? My gut says they should be < 5 mins, but no specific reason why.
