### ISSUE TITLE
use of environment variables in `dcpy` during builds

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#288]
per [this discussion](https://github.com/NYCPlanning/data-engineering/pull/269#discussion_r1349316650) during review of #269

## problems
- due to mixed use of the persistent or a temporary postgres DB, builds use environment variables in different ways
- setting relevant envars locally isn't straightforward
- for running builds, we'd like separation between "config" and "app" logic (see [Twelve-Factor App](https://12factor.net/) as a model)
- constructing/determining the name of a draft build (e.g. `dm-little-branch` or `pr_1000`) during the app logic violates this separation
  - especially if it involves invoking the git CLI

## considerations
- envars set by a python script are not applied to the higher-level environment that called the script. so bash scripts during a build will not reflect any envars set in an earlier python script

## TODO proposed approach
- set an environment variable before the "app" logic of the build begins?
- when python is to-be-run, check if a `.env` exists and use it if it does?

**Comment by damonmcc** [comment]
@alexrichey 

since the concern was about how we set envars, I searched the repo for `os.environ\[(.*?)\] =` and the only 3 results are in `dcpy/test/`. that seems like a reasonable place to have to set them

so, other than in tests, I suppose we set envars in github actions. perhaps we can close this issue and revisit the concern when we do more bash-to-python changes?

**Comment by alexrichey** [comment]
@damonmcc Agree, I think the intent here (basically, set env vars before we run the application) are pretty well satisfied
