### ISSUE TITLE
Tax Lot Tileset

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/data-engineering#292]
# Tax lot tileset
The tax lot tileset will have the structure shown below:

![tax-lot-tileset-diagram](https://github.com/NYCPlanning/data-engineering/assets/11068062/4e647c64-8a61-4a13-bfce-7f8bf72858f1)

#### Borough code
The borough field stores the borough id:
1 - Manhattan
2 - Bronx
3 - Brooklyn
4 - Queens
5 - Staten Island 

#### Block and lot
When shown on their own with pluto, block and lot ids will vary the digits used to represent them, based on the 'size' of the value. Block could have 1-5. Lot could have 1-4. When combined into a BBL, the block and lot values are padded with zeros to standardize the length of the BBL. The tileset should apply the same zero-padding technique to the block and lot fields.

#### BBL
In the original dataset, BBLs may have duplicates or act as placeholders. For the tileset, we would like to enforce the BBLs as unique identifiers for valid tax lots. To achieve this, borough, block, and lot values should be combined into BBLs that:
- Are unique within the tileset
- Represent a valid tax lot

### Label placement
The label should also be placed according to the [pole of inaccessibility](https://en.wikipedia.org/wiki/Pole_of_inaccessibility) using the polylabel [package](https://github.com/mapbox/polylabel) / [algorithm](https://blog.mapbox.com/a-new-algorithm-for-finding-a-visual-center-of-a-polygon-7c77e6492fbc)

This may require coercing multipolygons into polygons.

**Comment by TangoYankee** [comment]
Pinging @TylerMatteo for review of requirements

**Comment by TylerMatteo** [comment]
@fvankrieken The ideal min/max zoom for this is 15-22.

**Comment by fvankrieken** [comment]
Closing for now with merging of code completed so far.

Tracking this and related issues in a milestone now, with one remaining open ticket for optimization of tileset generation. Feel free to open up follow-up tickets and put the appropriate milestone
