### ISSUE TITLE
MapPluto subset as a DB

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/data-engineering#302]
# Description

Organize a subset of MapPluto into a normalized database with the structure shown below.

## Acceptance Criteria
For at least this iteration, Application Engineering is responsible for the creation and maintenance of the database. The role of data engineering will be to generate csvs which mirror the table structures that AE can then COPY into the database. The borough and land use csvs are small enough that it was feasible to create them by hand. So, DE will only need to generate the remaining csvs for tax lots and zoning districts.

- [x] There exists a folder on DO spaces with the csvs related to the following tables
  - [x] tax_lot
  - [x] zoning district
  - [x] zoning district class
    - [x] colors populated with the [zoning-district configuration in layers api](https://github.com/NYCPlanning/labs-layers-api/blob/develop/data/layer-groups/zoning-districts.json#L19) 
  - [x] zoning district to zoning district class (many to many relationship)   

***Note**: Zoning districts are intentionally excluded from the tax lot table. They will be related to tax lots through spatial joins performed when an end user requests zoning information about a tax lot*

![zoning-erd drawio](https://github.com/NYCPlanning/data-engineering/assets/11068062/f2d08dcd-faea-41cb-b1bb-bb0d93187a0a)

## Data sources
The majority of data comes from Map Pluto. However, geospatial data on zoning districts will need to be sourced from the zoning districts data set.

## Data descriptions
The data fields are sourced and structured as follows

- tax_lot table
  - bbl: from the MapPluto BBL field, with duplicate BBLs removed from the dataset
  - borough_id: from the MapPluto BoroCode field
  - block: from the MapPluto block field
  - lot: from the MapPluto block field
  - address: from the MapPluto address field
  - land_use_id: from the MapPluto LandUse field, structured to match the values in the land use table in the pluto data dictionary
  - wgs84: tax lot coordinates in wggs84 (epsg:4326)
  - li_ft: tax lot coordinates in Long Island (FT) (epsg:2263)
 
-  borough table ([borough.csv](https://github.com/NYCPlanning/data-engineering/files/12918384/borough.csv) for convenience)
   -  id: from the value listed in borocode table within the pluto data dictionary
   - title: from the description listed in borough table within the pluto data dictionary
   - abbr: from the value listed in borough table within the pluto data dictionary
- land_use table ([land_use_v1.csv](https://github.com/NYCPlanning/data-engineering/files/12918924/land_use_v1.csv) for convenience)
  - id:  from the value in the land use table within the pluto data dictionary
  - description:  from the description     in the land use table within the pluto data dictionary
  - color: land use from the existing zola layers
    - 1 is the octothorpe
    - 2-7 for rgb
    - 8-9 for opacity
    
- zoning_district table (sourced from [zoning district data](https://www.nyc.gov/site/planning/data-maps/open-data/dwn-gis-zoning.page))
  -  id: generated by the database
  - label: from the zonedist field of the Zoning District data
  - wgs84: zoning district coordinates in wggs84 (epsg:4326)
  - li_ft: zoning district coordinates in Long Island (FT) (epsg:2263)
  
- zoning_district_class table
  - id: From a list of each unique instance of a zoning code found through the [zonedist split process](https://github.com/NYCPlanning/data-engineering/issues/284#issuecomment-1759636648) (Each row should be a value like M1 or R7)
    - Similar to the Zone District Tilesets, it should exclude:
       - PARK
       - BALL FIELD
       - PUBLIC PLACE
       - PLAYGROUND
       - BPC
       - `null`
       - an empty string
  - category: The type of zoning district. 
    - **Enum** of `Residential`, `Commercial`, or `Manufacturing`
  - description: zoning class descriptions from [zola](https://github.com/NYCPlanning/labs-zola/blob/777cd81e5397e63984acbd081cafd037cd242fc4/app/components/layer-record-views/zoning-district.js#L3)
     - There exists class descriptions, such as R6, and contextual descriptions, such as R6A. For all contextual districts, the underlying class description should be used. We do not currently support zoning contexts.
     - The exception is R3, which does not have its own description. For R3, use a modified description of R3-1 districts:
     -  > R3 districts are the lowest density districts that allow semi-detached one- and two-family residences, as well as detached homes
  - url: (nullable) The full url to the planning website page that explains the zoning district. There are odd exceptions and accounting for them may be too time consuming for this iteration. In these cases, it is fine to leave them as null.  
  - color: zoning classes from the existing zola [layer groups](https://github.com/NYCPlanning/labs-zola/blob/07030aad23d60925d78c44fceed8075d94f5e9c2/public/layer-groups.json#L6188)
    - 1 is the octothorpe
    - 2-7 for rgb
    - 8-9 for opacity
- zoning_district_zoning_district_class table
   - Structures a many to many relationship between the tables of its namesake.

**Comment by TangoYankee** [comment]
pinging @TylerMatteo for confirmation of details

**Comment by TangoYankee** [comment]
Will make zoning district PK a UUID

**Comment by TylerMatteo** [comment]
@TangoYankee Looks good!

Some feedback:
* Thoughts on making the zoning district class category a [Postgres enum](https://www.postgresql.org/docs/current/datatype-enum.html)? [MikroORM supports them](https://mikro-orm.io/docs/defining-entities#enums). I can see an argument either way - having human-friendly strings like "Commercial" means we don't have to map the values to labels on the front end.
* Under Borough in Data descriptions, I think you meant "title", not "tile"

**Comment by TangoYankee** [comment]
@TylerMatteo Updated the ticket with zoning district id, zoning district class category, and borough title changes

@damonmcc A note on drawio svg v png; the first iteration of the ticket used svg. But, GitHub's rendering was ranging from awkward to unreadable. So, I swapped to png.

**Comment by TangoYankee** [comment]
@TylerMatteo If we want to account for colors of zoning districts and land use in the database, we could:

1) Break the zoning district category enum into a full table. Then, make a 'color' field on the created `zoning_district_category` table
2) Add a color field to the land use table

**Comment by TylerMatteo** [comment]
Based on our IRL discussions:
* Add 9-character length string columns to the land use and zoning district class tables
* Don't need a separate zoning district category table because the Zola behavior we're modeling after actually just picks the highest-numbered class within the category as the color for the category.

**Comment by TangoYankee** [comment]
@NYCPlanning/data-engineering updating zoning_district_class to have a description field

**Comment by TylerMatteo** [comment]
TODO for @TangoYankee - add a field to the zoning district class ERD for the URL to link to the public website page for that class. We're going to make it nullable to account for cases where we can't build a real link.

**Comment by TangoYankee** [comment]
> add a field to the zoning district class ERD for the URL to link to the public website page for that class. We're going to make it nullable to account for cases where we can't build a real link.

@NYCPlanning/data-engineering I recognize the description I gave for the url field is kinda lackluster but I'm not really sure how to explain it further. I am available for further clarification.
