### ISSUE TITLE
Implement Remaining Recipes Files

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#313]
Scope: Implement recipes files for remaining products (ie all except for Pluto and FacilitiesDB). 

This should be very straightforward. Facilities and Pluto (minor) were the odd cases. For the most part, it should be a matter of copying the requirements out of shell scripts. However, you may also need to check the QA steps, as these often pull in a previous version of the product from recipes to compare against. (these should also go in the recipes file)

I looked through the various products, and they looked straightforward. But we should scope this out, ie add checklists for the products to modify, and investigate any potential oddities. 

cc @fvankrieken from our retro conversation about lagging infra changes, e.g. recipes.

**Comment by alexrichey** [comment]
- [ ] cbbr
- [ ] checkbook
- [x] colp
- [ ] cpdb
- [ ] db-zap-opendata
- [ ] developments
- [x] facilities
- [ ] factfinder
- [ ] knownprojects
- [x] pluto
- [x] template
- [ ] zap-opendata
- [ ] zoningtaxlots

**Comment by fvankrieken** [comment]
I'm working on cpdb as part of fisa enhancements

**Comment by damonmcc** [comment]
I'll do KPDB soon, should be the last one!
