### ISSUE TITLE
2023-11 COLP Update

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#346]
# COLP Source Data Updates

Like most of our data products, source data must be updated in data library before COLP is run/built. 

All source data listed is to be uploaded as .sql files.

### Bytes of the Big Apple Source Data 
Make sure versions of each dataset are the most recent published version in DigitalOcean.

- [x] dcp_pluto - https://www.nyc.gov/site/planning/data-maps/open-data.page#pluto (Version that was last built and published, typically updated 4x a year)
- [x] dcp_colp - https://www.nyc.gov/site/planning/data-maps/open-data.page#city_facilities (Version that was last built and published)
- [x] dcp_boroboundaries_wi - https://www.nyc.gov/site/planning/data-maps/open-data/districts-download-metadata.page (New release with every geosupport but should not change from version to version)

### Manual Uploads
- [x] dcas_ipis - DCAS emails us a csv and this is ingested manually 

### Recieved via GIS Team uploaded to DO

- [ ] dof_air_rights_lots

**Comment by damonmcc** [comment]
reopened this to reflect the need to update this release on Socrata
