### ISSUE TITLE
DE<>GIS: Flow for DO -> Socrata

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#353]

**Comment by alexrichey** [comment]
Next Steps [As of Nov 20]:

OpenData

- [] replace metadata on push (Attachments)
- [] figure out versions/revisions weirdness
- [] QA what happens when data / column names / etc are changed.
- [] can we check/in and then push the column metadata (e.g. field descriptions)

**Comment by alexrichey** [comment]
Current Status:
Pushing a Shapefile to OpenData works just fine, but attachments (ie pdf metadata) isn't yet working. This may just be a limitation of the Python Socrata SDK. I can see that the [Java SDK](http://socrata.github.io/soda-java/apidocs/) has an `Attachment` object, which presumably can be pushed, so in theory the API has this ability. 

Worst case, metadata has to be attached manually when it changes .

**Comment by alexrichey** [comment]
Open questions:
- What GIS datasets are pushed to DO, but do or don't go to Socrata? / what's the venn diagram of DO and Socrata?
- from [the NYC Open Data dashboard](https://opendata.cityofnewyork.us/dashboard/) it looks like there are ~70 active datasets (active == updated in the last year or so)

**Comment by damonmcc** [comment]
can probably close this since #374 was merged?
