### ISSUE TITLE
ZAP Project BBL table missing records after 2018

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/data-engineering#368]
The zap_projectbbls.csv does not include records prior to 2018. Microsoft Platform Engineering (MPE) has confirmed that the data does exist in ZAP so we need to investigate why those records are excluded from the open data pull.

Ella from MPE noted that prior to 2018, Project IDs were 10 characters and started with a "P" (i.e. P2018Q0040) - could be a good starting point to see if we only allow Project IDs without P or only 9 digits. 

Another note, the Project ID in the zap_projectbbls.csv table concatenates Project ID + " - " + Boro + " - " + Block + " - " + Lot (i.e. "2019M0430 - 1 - 01421 - 0021"). 

Side note - we should only include the ZAP Project ID in the open data release, not the concatenated version above. I can open up a separate issue for that if that is desired.

Please reach out when someone from Data Engineering can look into this.

**Comment by damonmcc** [comment]
hey @croswell81 I'll look into this, and let's keep that side note Project ID bug in this issue since they're probably related

should we consider this is a relatively high priority issue?

**Comment by croswell81** [comment]
@damonmcc It is not high priority but Staten Island office is working on a project that would benefit from having this fixed sooner than later. If this work needs to scheduled in a sprint or two that is fine, but if there is capacity to fix in Sprint X (11/20-12/1) that would be great.

**Comment by damonmcc** [comment]
@croswell81 @NYCPlanning/gis I think I've found and fixed the problem. the latest outputs in Digital Ocean should have all BBL records (see screenshot [here](https://github.com/NYCPlanning/data-engineering/pull/424#issue-2045508768))

Note: we're talking about ZAP Projects and BBLs that are OK for public Open Data release, aka "visible"

**Comment by damonmcc** [comment]
this was closed automatically but will reopen it if GIS finds the issue hasn't been resolved
