### ISSUE TITLE
DE<>GIS: Spec s3 space for packaged GIS Assets

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#393]
This is the space where we'd store the results of our post-processing / packaging, prior to pushing to other data stores (ie Socrata, Bytes, SDE/AGOL). 

GIS had initially proposed a separate s3 space for this, but does it make sense to just package this within our existing `publish` versions?

In terms of file structure, the thought is to mimic the existing structure for products on the M drive.

**Comment by alexrichey** [comment]
This is now the edm-distributions space

**Comment by damonmcc** [comment]
current folder structure idea for the `edm-distributions` bucket is `dataset_name/version/destination_name/packaged files`
