### ISSUE TITLE
PLUTO QAQC potential bug with PLUTO versions

### ISSUE THREAD

**Issue by sf-dcp** [NYCPlanning/data-engineering#418]
For the current QAQC process, we use `latest` version recipes, including latest PLUTO version: 

![image](https://github.com/NYCPlanning/data-engineering/assets/144725249/be5b508f-0fdb-4384-9274-95c463b66aa6)

In the scenario when we re-publish same PLUTO version, the expected behavior is to use the previous version for QAQC. For example, we need to re-publish `23v3` and we would like to compare the output to the `23v2` version. However, with the current logic, QCQC will compare initial `23v3` version to the re-published `23v3`.

**Comment by fvankrieken** [comment]
Good catch. This isn't an issue with regards to 23v3 since we had not archived 23v3 with data-library yet, but this could absolutely cause issues down the road

**Comment by fvankrieken** [comment]
Actually, with current implementation in #413 this is covered

**Comment by sf-dcp** [comment]
nice! that was probably shortest lived issue
