### ISSUE TITLE
Regenerate AE tilesets, csvs

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#423]
https://github.com/NYCPlanning/ae-zoning-api/issues/111

- regenerate with correct path
- add all tileset fields to fill features

**Comment by damonmcc** [comment]
@fvankrieken can close this? I think you mentioned they were regenerated a couple days ago

**Comment by fvankrieken** [comment]
Likely going to do one more task as a part of this - just agree with AE on some sort of versioning
