### ISSUE TITLE
Plan Metadata and Data Dictionary

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#426]
We have metadata in the format that socrata expects for one product. We need to work backwards to derive a DCP base format, from which we'll generate the socrata metadata

**Comment by damonmcc** [comment]
because the feature would be helpful for testing metadata logic, I added "export as a shapefile" to the open Template DB enhancement issue https://github.com/NYCPlanning/data-engineering/issues/268
