### ISSUE TITLE
Push COLP to Socrata via automations

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#427]

**Comment by damonmcc** [comment]
there seem to be 3 distinct Socrata datasets for COLP ([search results here](https://data.cityofnewyork.us/browse?q=colp)). I stumbled onto this while working on the packaging stage that would come before pushing
- [Table](https://data.cityofnewyork.us/City-Government/City-Owned-and-Leased-Property-COLP-Table/fn4k-qyk2) with four-four `fn4k-qyk2`
- [Shapefile](https://data.cityofnewyork.us/City-Government/City-Owned-and-Leased-Property-COLP-Shapefile/2mhq-um7h) with four-four `2mhq-um7h`
- [Geodatabase](https://data.cityofnewyork.us/City-Government/City-Owned-and-Leased-Property-COLP-Geodatabase/c2g8-ercv) with four-four `c2g8-ercv`

**Comment by damonmcc** [comment]
per GIS comment [here](https://github.com/NYCPlanning/edm-overview/issues/1007#issuecomment-1875848678), COLP 23v2 is awaiting Socrata publishing

could do it manually (by emailing GIS or using the Socrate GUI) if we want to update Socrata asap

**Comment by croswell81** [comment]
@alexrichey Let's schedule some time to go over what prerequisites need to be completed and kick it off together. Can be done later this week.
@damonmcc

**Comment by alexrichey** [comment]
Outcome of Experiments to Push COLP:

Next Steps to Investigate:
- Use open revision on legacy COLP map type, and find way to upload a `geo` type source dataset
- Other APIs to push, instead of publishing (e.g. [DSMAPI](Dataset Management API)

 Next Steps - Concrete
- Add code to push csv and binary blob (unparsed, e.g. fgdb)
- Talk to OTI about deprecation/updating legacy version datasets
