### ISSUE TITLE
investigate FacDB source data for capacity/beds information

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#442]
to request missing data from agencies soon, we should:
- list source data for specified facility types
- compile a list that links to the latest source data file
- note if that source data has capacity and/or beds information

**Comment by fvankrieken** [comment]
See [here](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/cp/Shared%20Documents/03.%20Facilities/06.%20Special%20Projects/2023%20Bed%20-%20Pop%20Ratio%20Update/Residential%20Facilities%20FacType_2023.12.08.xlsx?d=wed3466963af0401d9c64ef330d0fba20&csf=1&web=1&e=7QNpHH&nav=MTVfe0UzMjZGM0EyLTUyQjgtNEExNi04NEE1LTg4RDlEMTcyQTkwRn0)

Previous sheet has linking of factype to data source
