### ISSUE TITLE
PFF source data complications

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#539]
Mainly getting some thoughts down around stuff going into #471. This could be part of #499.

## Motivation

PFF has presented some unique cases around updating source datasets. Currently, the PFF workflow largely consists of pivoting tabular data from excel sheets and concatenating/dumping into a csv. Relatively straightforward. However, there's a bit of complexity in terms of trying to map some of the entities into our current architecture. 

Mainly, this update is focused on ACS data. ACS has data for year 2010, then gets updates lagging slightly. So last year, we published 2021 data, this year we're updating with 2022. On the AE side of things, the desired end result is comparison of the latest data to the 2010 data. A year ago, these files were checked directly into the repo for simplicity. I archived them in data library as raw excel files just to move it a bit more to our desired state. So in DO, we have
- acs
  - 2010
    - acs.xlsx
  - 2021
    - acs.xlsx
  - 2022
    - acs.xlsx
However, this year, they also have some updated 2010 data. Specifically for one of the four sheets in the 2010 acs.xlsx. So first issue arises that "2010" is not a unique enough "version" of this dataset, since it can be updated. Second, it's a bit awkward to be updating just part of it - in our current system, the easiest way to do this would be to download the xl, replace the sheet, re-load. On the side of PFF/building, we need acs 2010 data, but the "latest" version of it, meaning "acs_2010" maybe needs to be its own dataset.

## Possible implementations

Thinking about our plans to archive raw source data, one possibility that might make sense is mapping one raw source dataset to multiple "recipe" datasets. These files really do have 4 datasets (social, economic, etc - the sheets within the xl), and in the current case, we really want to update just one of those. So assuming we have raw source data in `edm-inbox` for now, we could have something like

```mermaid
flowchart TB
  subgraph edm-inbox
    acs_2010/acs_2010_20230101.xlsx
    acs_2010/acs_2010_20240101_social_update.xlsx
  end
  data_library
  acs_2010/acs_2010_20230101.xlsx-->data_library
  data_library_2
  acs_2010/acs_2010_20240101_social_update.xlsx-->data_library_2
  subgraph edm-recipes
    acs_2010/20230101/acs_2010.parquet
    acs_2010/20240101/acs_2010.parquet
  end
  data_library-->acs_2010/20230101/acs_2010.parquet
  acs_2010/20230101/acs_2010.parquet-->data_library_2
  data_library_2-->acs_2010/20240101/acs_2010.parquet
```

Then at build time, we simply look for latest acs_2010. This is maybe a tad clunky - I don't love updating a dataset with itself in general, and only conditionally. Not quite sure what this would look like in terms of a library template yml/python script, needing to sometimes just grab raw data only, sometimes append, etc.

It might be nicer to go with

```mermaid
flowchart TB
  subgraph edm-inbox
    acs_2010/acs_2010_20230101.xlsx
    acs_2010_social/acs_2010_20240101_social_update.xlsx
  end
  data_library
  acs_2010/acs_2010_20230101.xlsx-->data_library
  data_library_2
  acs_2010_social/acs_2010_20240101_social_update.xlsx-->data_library_2
  subgraph edm-recipes
    acs_2010_social/20230101/acs_2010_social.parquet
    acs_2010_economic/20230101/acs_2010_economic.parquet
    acs_2010_social/20240101/acs_2010_social.parquet
  end
  data_library-->acs_2010_social/20230101/acs_2010_social.parquet
  data_library-->acs_2010_economic/20230101/acs_2010_economic.parquet
  data_library_2-->acs_2010_social/20240101/acs_2010_social.parquet
```

Then at build time, acs_2010_social and acs_2010_economic are both inputs, and latest can be grabbed separately for each.
This would then need a template yml for each of the sub-datasets of course, and there still is some conditionality - maybe just name of the excel file and the sheet to look at. But those two things are relatively easily parameterizable. It's maybe a tad inelegant in our current framework that after loading a "complete" acs dataset to edm-inbox, you'd have to run multiple data library jobs, each opening this bulky excel file. Maybe more ideally, there's one data library job that is triggered by uploading a dataset (or other trigger for non-manual files) that can then process and spit out multiple recipe datasets, but that's certainly way outside our infrastructure at the moment, and we'd have to think about how that gets configured - 1 yml file per recipe dataset, and something separate for the raw data processing job? Seems like better to go with something that aligns just a tad better with our current system for now

**Comment by alexrichey** [comment]
@fvankrieken sounds like you're leaning toward option 2, for conceptual simplicity? I think it makes sense

**Comment by fvankrieken** [comment]
Yeah. Originally I was trying to think about actually mapping 1 source to multiple recipe datasets more from the perspective of the source, if that makes sense. Like run 1 job to populate 4 recipe datasets. But that just seems like a bit of a mess right now, whereas the second option here as described can fit fairly cleanly into what we're working with now

**Comment by fvankrieken** [comment]
Other drawback is that we start having lots of datasets for this. `acs_2010`, `acs_2019`, `acs_2020`, `acs_2021` all being distinct datasets

**Comment by alexrichey** [comment]
@fvankrieken Gotcha - that doesn't seem too terrible, though
