### ISSUE TITLE
DE<>GIS: FacDB Collab - Metadata and Socrata Push

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#623]
When we last spoke, we decided that with COLP pushing to -> Socrata, we should start widening the process out to include other products. Facilities Database was seen as a natural choice, since it has some complications, and we just built it, so it's fresh in our minds. 

For this issue, DE would work with someone from GIS to create the metadata, and set up the push to Socrata.

**Comment by damonmcc** [comment]
(per comment [here](https://github.com/NYCPlanning/data-engineering/issues/800#issue-2264083866)) closing this in favor of issues for batches of datasets
