### ISSUE TITLE
Data Library - Convert raw data to parquet

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#631]
This should take result of #499 and convert it to parquet. This will obviously depend on file type, as defined in `source` section of yml template. For shapefiles, geodatabases, etc. it might still make sense to use gdal, though geopandas is an option as well. In my opinion, code simplicity is most important, so even if gpd is less performant (not sure it is, just speculating), I would prefer it to gdal. 

This should output a parquet file locally that can feed into the preprocessing steps of the extraction

**Comment by fvankrieken** [comment]
Edge cases:
- geodatabase with multiple layers where we only need one of them

**Comment by sf-dcp** [comment]
Adding on requirements for this task: 

* Reading in the following formats:
  * csv
  * geodabase (with 1 or multiple layers)
  * shapefile
  * zipped version of any of the formats above
  * json
  * geojson
  * excel?
  
* Correct geometry in output (parquet stores geometry in wkb format)
* Unchanged column names in output
* Unchanged data in output

**Comment by sf-dcp** [comment]
Update: implemented 1st iteration of `convert_raw_to_parquet` fn in #658. The fn currently converts `csv`, `geodatabase`, and `shapefile` formats to parquet. 

`TODO`:  
- [ ] implement json
- [ ] geojson
- [ ] zipped format
- [ ] for csv files, implement point geom made out of Longitude & Latitude columns
- [ ] geoparquet (as an export format)
- [ ] name geometry column as `geom` in output parquet file
- [ ] break up `transform_to_parquet` fn into 2 parts: 1) read raw data into a `geopandas` df and 2) save the df to parquet
- [ ] simplify tests (perhaps by using complete, not partial, fake templates)

**Comment by fvankrieken** [comment]
For raw json, it'd make sense to have an optional field that takes input in form of jq query to parse a slightly nested structure into something tabular

**Comment by sf-dcp** [comment]
All data formats have been implemented.
