### ISSUE TITLE
Data Library - Processing Scaffolding

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#632]
Per https://github.com/NYCPlanning/data-engineering/issues/484#issuecomment-1969720450, set up for now at least a scaffold of code to take yml template and run custom script (if called for), geoprocessing steps, etc.

**Comment by sf-dcp** [comment]
From [review](https://github.com/NYCPlanning/data-engineering/issues/633#issuecomment-1973433345) of custom scripts, the following set of templates seem to be representative of our custom scripts ingestion: 

* `nysed_nonpublicenrollment` <-- data read from a specific tab in an excel file
* `dcp_pad` <-- extract zipfile from an API
* `bbl_libraries` <-- extract json from an API
* `doe_pepmeetingurls` <-- scrapes data from a website with requests & beautiful soup. This recipe represents datasets that can't be simply pulled, and we need to account for the logic with a custom script extraction.
* `fisa_capital_commitments` <-- a csv with custom delimiter & no headers. Similar datasets also require custom encoding when reading from a csv. 

cc: @fvankrieken
