### ISSUE TITLE
PLUTO: Incorporate manual research

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/data-engineering#657]
During the 24v1 creation records were identified where should be modified based on research:
1) 5008640515 building area value changed from 250 to 28500
Research top offenders from Unreasonably small apartments table and make modifications

**Comment by damonmcc** [comment]
will do in next major build

**Comment by fvankrieken** [comment]
This actually seems that it has the correct value now - calculating area with postgis gives 31718 sq feet. Given that the lot is roughly 250x150 (not actually square), the new value seems correct rather than 250 sq ft

**Comment by fvankrieken** [comment]
And to clarify, bldgarea stayed consistent, lot area changed from 250 to 28500 between 23v3 and 24v1

We could calculate lot areas based on geom and include that as an automated check

**Comment by fvankrieken** [comment]
Thanks, I did not think about the fact that github would still see that as "{irrelevant text} close #&#x2060;657". Though actually I've begun tracking corrections in #831 and this specific issue doesn't actually require correction, so on that note I'll reclose it
