### ISSUE TITLE
DE<>GIS Automations - Phase 2

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#663]
### Project Description

We've set up the scaffolding to automate the push to Open Data and do validation on datasets. Now we need to implement this for all our (and GIS's) products.

### Outcomes

The deployments to Socrata are entirely automated for all products.

### Timing

This will require a lot of coordination, and modification to existing datasets to fix issues. This will take months.

### Tasks

Tracking [here](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/itd/edm/_layouts/15/Doc.aspx?sourcedoc=%7B6735537B-8D8E-437A-B5E5-3A6B54194B24%7D&file=Open_Data.xlsx&action=default&mobileredirect=true)
(last column)

#800 

### Motivations

...

### Notes

...

**Comment by damonmcc** [comment]
## notes from 4/23

- let's use the progress indicators from the GDE biweekly
- having files in `edm-distributions` bucket is important (whether it's for an API or manual distribution to Socrata)
- Socrata dataset types
  - old map types block API use
  - to deprecate, we'd like to make an old dataset "useless" and point to the dataset that replaces it
    - prepend title with something like `DEPRECATED`
    - change description to point to new dataset
    - update with row-less data
- datasets to prioritize
  - those that GIS is scheduled to update soon and/or monthly

## next steps
- ask GIS about their upcoming dataset updates
- confirm automation progress goals and track (possibly in Open Data excel sheet)
- ask GIS to choose a project lead to streamline comms and planning

**Comment by alexrichey** [comment]
Also adding: goal of automations is 80% by end of Q2 (July 1). 100% by Q3, per Strategic Planning

**Comment by alexrichey** [comment]
@croswell81 FYI, this is our main issue for the project.

**Comment by croswell81** [comment]
[like]  Matthew Croswell (DCP) reacted to your message:
________________________________
From: Alex Richey ***@***.***>
Sent: Wednesday, April 24, 2024 9:12:34 PM
To: NYCPlanning/data-engineering ***@***.***>
Cc: Matthew Croswell (DCP) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NYCPlanning/data-engineering] DE<>GIS Automations - Phase 2 (Issue #663)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.  Forward suspect email to ***@***.******@***.***> as an attachment (Click the More button, then forward as attachment).


@croswell81<https://github.com/croswell81> FYI, this is our main issue for the project.
