### ISSUE TITLE
add remaining Green Fast Track variables

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#664]
see meeting notes [here](https://github.com/NYCPlanning/edm-overview/issues/1012#issuecomment-1967427682) and source data spreadsheet [here](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/itd/edm/_layouts/15/Doc.aspx?sourcedoc=%7BBAE15377-87A6-4188-9637-36A89AC1DF98%7D&file=CEQR_Type_II_Data_Source_Review.xlsx&action=default&mobileredirect=true)

### extract new source data

- [x] #674
- [x] #672
- [x] #673
- [x] Exposed Rail Yards
- [x] NYCDOB Tidal Wetland
- [x] NYCDOB Freshwater Wetland
- [x] NYCDOB Coastal Erosion Hazard Area

### adding logic for new variables
- [x] #732 (added by @sf-dcp on 4/3/24)
- [x] Natural Resources
- [x] Historic Resources
- [x] Exposed Rail Yards
- [x] NYCDOB Tidal Wetland
- [x] NYCDOB Freshwater Wetland
- [x] NYCDOB Coastal Erosion Hazard Area

### exporting new source data
- [x] export all new source data in FGDB

---

### GFT dataset details
- The primary GFT table has a row for each PLUTO lot and columns to represent each "GFT variable". These variables are grouped into "CEQR categories".
- For each variable, there's a single binary flag column and at least one value column.
- When a variable flag is "Yes", the variable value columns show the source data values that contribute to the flag.
- Each GFT variable has one source dataset.
- `Category -> Variables -> Source`

### more GFT dataset details
- We have a CSV to describe all GFT variables [here](https://github.com/NYCPlanning/data-engineering/blob/main/products/green_fast_track/seeds/variables.csv).
  - It maps each variable to a category.
  - Each variable has at least source.
  - `Category -> Variables`
- Other than combing through sql code, we don't yet have the `Variable -> Sources` mappings documented (similar to the [source data excel file](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/itd/edm/_layouts/15/Doc.aspx?sourcedoc=%7BBAE15377-87A6-4188-9637-36A89AC1DF98%7D&file=CEQR_Type_II_Data_Source_Review.xlsx&action=default&mobileredirect=true)).

### Potential approach to confirming existing variables
1. Ensure records in [`variables.csv`](https://github.com/NYCPlanning/data-engineering/blob/main/products/green_fast_track/seeds/variables.csv) cover all expected GFT variables by comparing it to the [source data excel file](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/itd/edm/_layouts/15/Doc.aspx?sourcedoc=%7BBAE15377-87A6-4188-9637-36A89AC1DF98%7D&file=CEQR_Type_II_Data_Source_Review.xlsx&action=default&mobileredirect=true))

### Potential approach to adding a new/missing variable (builds/tests fail until the last step)
1. Add a record to the [`variables.csv`](https://github.com/NYCPlanning/data-engineering/blob/main/products/green_fast_track/seeds/variables.csv)
2. Create a `dcpy/library/templates/` YAML file for the source (if needed)
3. Add the source to `recipe.yml` and `_sources.yml` (if needed)
4. Create a staging model by listing it in the properties file and adding a script (if needed)
5. Create a new intermediate model and test `variable_id` for `null` and `unique`
6. Add the new intermediate model to the list in `int_buffers__all`
7. Update and review the pilot project records in [`test_expected_pilot_projects.csv`](https://github.com/NYCPlanning/data-engineering/blob/main/products/green_fast_track/seeds/test_expected_pilot_projects.csv) by copying the table the csv was compared to

**Comment by damonmcc** [comment]
(not vital, just a thought)

for geometries that are eventually checked for intersections with all lots during `int__spatial_flags`, it may be nice to distinguish between buffered polygons and polygons before that model uses them

they could all still end up in the same table, but that table is currently called `int__all_buffers`

**Comment by damonmcc** [comment]
after new Shadows data has been added to GFT, the DAG with the filter `--select intermediate` is below.

while adding logic to use the new data, I'll try to add a test we've talked about which would warn or error when new variables like `nyc_parks_properties` don't appear in the final table

<img width="836" alt="Screenshot 2024-03-29 at 7 53 42 AM" src="https://github.com/NYCPlanning/data-engineering/assets/7444289/a3c43661-67e9-4526-a7ab-62a5f5dea9f2">

**Comment by damonmcc** [comment]
for some reason during the ST_INTERSECTS part of `int_flags__spatial`, each lot is "intersecting" twice with polygons from `int_buffers__nys_parks_properties`

![Screenshot 2024-04-02 at 5 19 47 PM](https://github.com/NYCPlanning/data-engineering/assets/7444289/df7b30fc-1bd3-4360-a3a8-7a07d4e3842a)

the buffered NY State Parks polygons seem ok though

**Comment by fvankrieken** [comment]
> for some reason during the ST_INTERSECTS part of `int_flags__spatial`, each lot is "intersecting" twice with polygons from `int_buffers__nys_parks_properties`
> 
> ![Screenshot 2024-04-02 at 5 19 47 PM](https://private-user-images.githubusercontent.com/7444289/318964629-df7b30fc-1bd3-4360-a3a8-7a07d4e3842a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTE2MDIsIm5iZiI6MTcxMjE1MTMwMiwicGF0aCI6Ii83NDQ0Mjg5LzMxODk2NDYyOS1kZjdiMzBmYy0xYmQzLTQzNjAtYTNhOC03YTA3ZDRlMzg0MmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMTMzNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM5NTExNWQyYWE1YTE4MGUwNGE1YjUxZjJkOTQ4NTE2ZWU0ZmM2MzRjMTI5MzNiNGI5NjVmZWUxMzEzY2E5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Gn6yI9uRghOQKzUfAC8i1rqbQ60sepd2bL8-F-QLj28)
> 
> the buffered NY State Parks polygons seem ok though

Was curious if there was an odd data issue so poked around. Duplicated line [here](https://github.com/NYCPlanning/data-engineering/pull/727/files#diff-b9d6d8d271e090af5c23bfda37e5d7edd664aaeabd361074c6645a476820bd96R10)!

**Comment by damonmcc** [comment]
looks like `int_buffers__us_parks_properties` is actually just `stg__nys_parks_properties`, so the union all in `int_buffers_all` has duplicates

![Screenshot 2024-04-03 at 10 17 11 AM](https://github.com/NYCPlanning/data-engineering/assets/7444289/375b0b56-09a7-4264-a8e1-e3f8ec3d15da)

**Comment by sf-dcp** [comment]
> looks like `int_buffers__us_parks_properties` is actually just `stg__nys_parks_properties`, so the union all in `int_buffers_all` has duplicates
> 
> ![Screenshot 2024-04-03 at 10 17 11 AM](https://private-user-images.githubusercontent.com/7444289/319224312-375b0b56-09a7-4264-a8e1-e3f8ec3d15da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTY5MTcsIm5iZiI6MTcxMjE1NjYxNywicGF0aCI6Ii83NDQ0Mjg5LzMxOTIyNDMxMi0zNzViMGI1Ni0wOWE3LTQyNjQtYThlMS1lM2Y4ZWMzZDE1ZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMTUwMzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2I0YmUwODFjMGM5ZDQ5ZGNmNGExOTY2MDRiNzhjZDBkZjE5MTY5MDJkYzc1MGJiNzJiY2I5YWFiZTIxYzQwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nzl2PxSIRW2YkkLQYDAOARL-N12cS0rT6oTv-KzZsLs)
> 
> @sf-dcp looks like we can drop the `int_buffers__us_parks_properties` model? I don't see any mention of US Parks in GIS's source data excel sheet

Wow that's a great catch! `int_buffers__us_parks_properties` doesn't use correct stage table. It should use `stg__us_parks_properties` instead. US Parks is listed **Federal Parks property** in the GIS spreadsheet

**Comment by sf-dcp** [comment]
> > for some reason during the ST_INTERSECTS part of `int_flags__spatial`, each lot is "intersecting" twice with polygons from `int_buffers__nys_parks_properties`
> > ![Screenshot 2024-04-02 at 5 19 47 PM](https://private-user-images.githubusercontent.com/7444289/318964629-df7b30fc-1bd3-4360-a3a8-7a07d4e3842a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTE2MDIsIm5iZiI6MTcxMjE1MTMwMiwicGF0aCI6Ii83NDQ0Mjg5LzMxODk2NDYyOS1kZjdiMzBmYy0xYmQzLTQzNjAtYTNhOC03YTA3ZDRlMzg0MmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMTMzNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM5NTExNWQyYWE1YTE4MGUwNGE1YjUxZjJkOTQ4NTE2ZWU0ZmM2MzRjMTI5MzNiNGI5NjVmZWUxMzEzY2E5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Gn6yI9uRghOQKzUfAC8i1rqbQ60sepd2bL8-F-QLj28)
> > the buffered NY State Parks polygons seem ok though
> 
> Was curious if there was an odd data issue so poked around. Duplicated line [here](https://github.com/NYCPlanning/data-engineering/pull/727/files#diff-b9d6d8d271e090af5c23bfda37e5d7edd664aaeabd361074c6645a476820bd96R10)!

It doesn't seem to be duplicated as NYS and NYC properties are different

**Comment by damonmcc** [comment]
notes from DE & GIS chat on 4/2


## Zoning, Lot info

- R1-R4 can exist with C or M
- R5-R10 cannot exist with C or M
- for current NULL values use one of these: Inelidgable, Not Applicable, Other

## Natural Resources (Finn)

- survey questions:
  - does your porject site contain a natural resources?
  - is your project site near a wetland check zone?
  - Are you near another ... ? (not data-driven)
- App Table vs Output CSV
  - show single binary Natural Resources answer
  - show all columns related to that answer

## Historic Resources (Alex)

- distinction b/w resource and district
  - resource = point
  - district = polygon
- "does your project contain" (look for points)
- "are you near" (buffer lots that contain points or buffer points)

## Rail

- GRU is gonna make changes for 24B

## Rail Yards

- GIS can use polygons (Complex Polygons)
- not in CSCL because they're Complexes

## Beaches

- Non-DPR parks have no names

**Comment by croswell81** [comment]
@sf-dcp 

- **Federal Parks Property**: you should only use parks within NYC, so don't worry about the ones not in NYC. If there are future null values, we are still using the park name [PARKNAME] so the value will not be completely null.
- **NYS Parks Property**: just cleared this up. There are no current records in Manhattan (aka New York county) but we should include it in the filter in case one is created in the future. If there are null values, we are still using the park name [Name] so the value will not be completely null.
- **NYC Parks Property**: Good catch! Cemetery should be filtered out, I updated the data source doc.
- **WPAA**: It looks like there is an alias field name for status as **construction status**. Let us know if you don't see either field.

**Comment by sf-dcp** [comment]
Update as of 4/9/24: Shadows/Open Space logic has been implemented except 1 outstanding item (filter WPAA data by status). It appears that WPAA recipe currently uses incorrect Esri link to pull the data, and this is why the `status` column is absent.

`TODO`:
- [ ] update WPAA recipe with new esri link and archive
- [ ] update logic for WPAA table to filter by status

**Comment by croswell81** [comment]
@sf-dcp the link to the wpaa rest feature service that will be updated is: https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/nywpaa/FeatureServer/0

**Comment by croswell81** [comment]
@sf-dcp BYTES has also been updated with the correct link now.

**Comment by damonmcc** [comment]
from @croswell81 

> New Natural Resources dataset. Three check flag fields from DOB, I added each as a separate dataset in the CEQR Type II Data Source Review doc. They are NYCDOB Tidal Wetland, NYCDOB Freshwater Wetland, NYCDOB Coastal Erosion Hazard Area. 
>  
> One table with bbl and flag (X or null) field for each variable. Join to PLUTO and create a lot based dataset for each of the three variables.

**Comment by fvankrieken** [comment]
Just adding todos in one place for myself, a bit redundant but just for convenience.

- [ ] archive nyc_beaches_20240509.zip
- [ ] archive railyards_hudsonyards_erase.zip with an informative name
- [ ] archive above 4 datasets
- [ ] add logic for railyards
- [ ] add logic for remaining natural resources

**Comment by damonmcc** [comment]
@jackrosacker @caseysmithpgh just tagging yall here because you'll have to add aliases for 3 new rows in the `source_data_versions` table

**Comment by fvankrieken** [comment]
@jackrosacker - the data from DOB is just a wide table of flags per bbl. Do you still want this exported with the source data in some way? It's a bit different from say CATS permits, where we look up a bbl but actually use that geometry to create a buffer, rather than just using the source dataset to determine if there's a flag. This is more like E-Des in that way. So if it sounds good, I think it would just make sense to include these flags in the final table without exporting a source layer.

But of course, if it'd be useful to have a feature that's every lot that has these specific flags, we can easily add that. let me know

**Comment by damonmcc** [comment]
@fvankrieken 
> @jackrosacker - the data from DOB is just a wide table of flags per bbl. Do you still want this exported with the source data in some way? It's a bit different from say CATS permits, where we look up a bbl but actually use that geometry to create a buffer, rather than just using the source dataset to determine if there's a flag. This is more like E-Des in that way. So if it sounds good, I think it would just make sense to include these flags in the final table without exporting a source layer.

(after chats with @jackrosacker and @fvankrieken)

E-Des is a good comparison for these tabular (rather than spatial) variables. we won't export source data layers for tabular variables

and since the new Exposed Rail Yards will be an input to the existing Exposed Railway question/flag, this are the potential export layer impacts
- if Exposed Rail Yards is polygons, add a new model/layer named `source__exposed_railway_polygons`
- if Exposed Rail Yards is polygons, `source__exposed_railway_lines` will have more records
- either way, the single record in `source__exposed_railway_buffer` will increase in area

**Comment by fvankrieken** [comment]
@damonmcc thanks for the clear write-up. They're polys. These two have the same `flag_id_field_name` then, should they have the same `variable_type` as well? I would lean with keeping them distinct here, but if you think it aligns better with other things to have them the same that's fine too.

Re the dob natural resource flags - these will just get wrapped up in the other natural resources, correct? And if so, what should their variable_type and variable_id be? Since there's one row per bbl in the dataset (so each bbl can only have one at most "NYCDOB Tidal Wetland" flag), maybe just have variable type and id be the same for legibility? "nycdob_tidal_wetland"? or something like that?

**Comment by damonmcc** [comment]
@fvankrieken 

for Rail Yards; agree that a distinct `variable_type` makes more sense

for the DOB natural resource flags: ...

**Comment by jackrosacker** [comment]
> E-Des is a good comparison for these tabular (rather than spatial) variables. we won't export source data layers for tabular variables

In order to symbolize the DOB features on the map, will they be exported as part of the unioned Natural Resources dataset, or am I understanding that since these are per-lot attributes you won't be exporting any data and I should be displaying a view of the lots dataset with each DOB lot flagged?

**Comment by damonmcc** [comment]
cc @fvankrieken 

let's keep this open until a recent build is successfully used in the app
