### ISSUE TITLE
archive GFT Natural Resources data

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#672]
Archived
- [x] State Regulated Freshwater Wetlands and Checkzone
  - [x] checkzone specifically 
- [x] Tidal Wetlands
- [x] Priority Waterbodies
- [x] Significant Natural Communities
- [x] Beaches
- [x] National Wetlands Data

GFT Logic written
- [ ] State Regulated Freshwater Wetlands and Checkzone
- [ ] Tidal Wetlands
- [ ] Priority Waterbodies
- [ ] Significant Natural Communities
- [ ] Beaches
- [ ] National Wetlands Data

other
- [x] `variables.csv` updated

**Comment by fvankrieken** [comment]
@croswell81 @jackrosacker - state-regulated freshwater wetlands comes with a buffer, the described "check zone" described [here](https://services6.arcgis.com/DZHaqZm9cxOD4CWM/arcgis/rest/services/State_Regulated_Freshwater_Wetlands/FeatureServer). It is "a minimum of 100 feet, but has been extended for a limited number of particularly sensitive wetlands". In our excel file, we state a buffer of 100 feet - should I just go with 100 feet, or use the supplied check zones?

**Comment by jackrosacker** [comment]
The data source sheet may need to be edited to consider the wetland and check zone sources as two different datasets and questions. Alex M. confirmed that the check zone question has distinct implications and would need to be asked regardless of the answer to the wetland+ question. 

The preliminary language we have for these is:
- Does your project site contain a [Natural Resource]?
and
- Is your project site within a wetland check zone?

We still need to vet and finalize the language and data categorization here, but from what's been communicated to us it sounds like either a project **contains** a wetland, and/or the project is **within** a wetland check zone. I'd tentatively say that we wouldn't need to calculate 100' buffers, but would just look for a spatial relationship between each lot and the existing check zone polygons.

Matt may have some different info on this - curious to check in later today.

**Comment by croswell81** [comment]
I need to clean-up the natural resources and open space sections of this document. Might be helpful for us to check-in and discuss what's left so we are all on the same page of what is final and what might need some clarification from either Planning Support or EARD.
@fvankrieken @jackrosacker

**Comment by fvankrieken** [comment]
I think it'd be good to chat at some point today. There's also this comment in the natural resources section
> SS wants to touch base with Parks and see if they can share their dataset to avoid duplication
But curious in general around thoughts on duplication - with tidal wetlands, shorelines, and beaches there's certainly going to be a lot of it. Maybe it makes most sense for us first to pass this data all through to you (with all tidal_wetlands buffered combined into one geom, all shorelines, etc) and use that as a starting point for discussion. I could have that done by some point tomorrow hopefully

**Comment by fvankrieken** [comment]
For now we could just aggregate -> comma separated list of all natural resources.

**Comment by fvankrieken** [comment]
Also, I see beaches are pending - should I ingest those two datasets and use them for now? Or leave those out for the moment

**Comment by croswell81** [comment]
I definitely have time to meet today. I have a beaches dataset created now but needs some final clean-up before I share. 

I'd like to go through historic, natural resources, and open space. I haven't had time to update the spreadsheet but maybe we can do that in a meeting. My afternoon filled up but can meet after 3:30. @jackrosacker should attend also.

**Comment by fvankrieken** [comment]
We've split up those 3 between me (natural resources), Alex (historic) and Sasha (open space). Let's aim for either tomorrow afternoon or Monday to check in to make sure we have all our questions in order? I'll organize the above thoughts a bit more succintly for whenever we meet

**Comment by fvankrieken** [comment]
Main questions for meeting
- How to present data? For now, all natural resources
- Distinction of "contains" vs buffer intersection
- Check zone only exists for freshwater wetlands - use check zone for it, buffer for others?

Are we skipping
- Priority Estuaries - "almost identical to tidal wetlands"
- National wetlands - "Overlaps with most of the Priority Waterbodies and Tidal Wetlands, does not include name of feature - recommend to skip unless it is known to have features not inlcuded in STATE"

Meeting notes:
- potentially redundant datasets - just include for now, maybe drop later if we decide they're redundant
- separate flag for wetlands checkzone
- rest get aggregated. Put out source data in export for each
