### ISSUE TITLE
FacDB: pick recipe 

### ISSUE THREAD

**Issue by sf-dcp** [NYCPlanning/data-engineering#690]
While getting Shadow category recipes for the Green Fast Track product, I realized that one of the needed datasets, NYS Parks Property, may be already present in data library (`nysparks_parks`). I did end up pulling the requested data from a different source chosen by the GIS into a new recipe `nysparks_parks_polygons` as these datasets had different geometries and different row count. 

### Motivation
FacDB uses `nysparks_parks` recipe and we should re-evaluate whether we continue using this recipe or should switch to `nysparks_parks_polygons ` instead. 

### Info on the recipes: 
* `nysparks_parks `
    * Source: https://data.ny.gov/Recreation/State-Park-Facility-Points/9uuk-x7vh
    * Geometry: point
    * Row count: 254
    * Last updated (as of 3/15/24): 12/7/2020

* `nysparks_parks_polygons`
    * Source: https://data.gis.ny.gov/datasets/nysparks::ny-state-parks-property/about
    * Geometry: polygon
    * Row count: 860
    * Last updated (as of 3/15/24): 2/1/2024

### Timeline
Until next FacDB build (May 2024?)

**Comment by alexrichey** [comment]
Same situation for `nysparks_historicplaces`. This is a Socrata datasource, but the ESRI version is more recently updated, with more rows. We use the newer version `nysparks_historicplaces_esri` in GFT, and need to swap it out in FacDB as well.

**Comment by damonmcc** [comment]
gonna make the change to use `nysparks_parks_polygons` and `nysparks_historicplaces_esri` as part of the 24v2 build ([data update issue](https://github.com/NYCPlanning/data-engineering/issues/989))
