### ISSUE TITLE
use GFT pilot project to test data pipeline

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#708]
Potential Green Fast Track pilot projects have been identified by Planning Support to be used in training materials.

To ensure we generated expected outputs, we could use these sets of lots as the focus of an integration test for our GFT builds.

We could use any lots for this type of test. But using pilot project lots would mean that their outputs will be accurate while DCP uses them in training materials and we're likely to get quick feedback on any questions we have about expected outputs.

**Comment by sf-dcp** [comment]
@damonmcc, could you explain here or offline what kind of projects Planning Support selects and what it means them using the projects in training materials?
