### ISSUE TITLE
some data products in mono repo fail to build

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#72]
see [Data Catalog](https://github.com/NYCPlanning/data-engineering/wiki/Data-Catalog) for list of our primary data products in the mono repo and if they are currently building here

resolving this is intended to ensure that all products in the mono repo are built and maintained in it and to allow the archiving of the dataset-specific repos

- ZTL
  - [data loading fails](https://github.com/NYCPlanning/data-engineering/actions/workflows/zoningtaxlots_dataloading.yml) due to working directory
  - [build fails silently](https://github.com/NYCPlanning/data-engineering/actions/runs/5648705784/job/15301493492#step:6:41) during `pg_dump`
- KPDB
  - [build action](https://github.com/NYCPlanning/data-engineering/actions/workflows/knownprojects_build.yml) hasn't been touched since it was copied in
- PFF is in-progress

**Comment by fvankrieken** [comment]
There's a checklist for ztl here

https://github.com/NYCPlanning/data-engineering/issues/43
