### ISSUE TITLE
Peculiar Zoning Tax Lot QA results

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/data-engineering#753]
### Summary
GIS Team ran zoning tax lot QA today and ran into four lots with abnormal results that may be worth inspecting. All four lots show tabular zoning changes, but no associated changes in the zoning overlay. In all four cases, the changes are an improvement, and increase the accuracy of the zoning values, but it is unclear how the erroneous data existed before without being caught, and why the latest ZTL/PLUTO build is adjusting the values now. 

For example: BBL 2032440145 flipped the ZD1/ZD2 values, because previously the zd that covered the lesser portion of the lot was incorrectly listed as the ZD1. 

[Relevant Action run](https://github.com/NYCPlanning/data-engineering/actions/runs/8558129132/workflow)
### Example data
bblnew | zd1new | zd2new | zd3new | zd4new | co1new | zd1prev | zd2prev | zd3prev | zd4prev | co1prev
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1013980061 | R8B | C1-8X |   |   |   | R8B |   |   |   |  
2032440145 | M1-1 | M3-1 |   |   |   | M3-1 | M1-1 |   |   |  
3035870001 | R6 |   |   |   |   | R6 | R7-2 |   |   | C2-4
4027740024 | R5B | R4-1 |   |   | C1-2 | R5B |   |   |   | C1-2

This is not urgent. We're passing ZTL QA since all four of these "errors" are improving data quality, but creating this issue anyway since they may indicate a blind spot in our process.

**Comment by fvankrieken** [comment]
Zola currently shows 2032440145 as more in an M3-1, implying that's likely a real change (at least from versions currently on zola - so from Pluto 24v1 at least, or January/Feb ZTL

![image](https://github.com/NYCPlanning/data-engineering/assets/9454672/8b010fd8-8df2-4c19-b57b-06d9c0799860)

**Comment by fvankrieken** [comment]
So a dtm lot change?

**Comment by fvankrieken** [comment]
Looks like it merged with the lot above it (sorry for ugly projection/colors in qgis)

![image](https://github.com/NYCPlanning/data-engineering/assets/9454672/099a627b-5872-4690-b18f-ec6fd7fcf14b)

**Comment by fvankrieken** [comment]
Due to issues around our publishing, latest was being compared to outdated ztl
