### ISSUE TITLE
CBBR 2024

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#754]
### Product Name

cbbr

### Build Version

2024

### Status of Update

- [x] source data extracted
- [x] draft build succeeded
- [x] draft build passed QA
- [ ] data packaged and distributed

**Comment by fvankrieken** [comment]
Comparing build `fvk-cbbr` to `30-fix-yaml-file` (our oldest remaining draft - we don't have any "publish" datasets, things seem consistent

Last year
- 3727 rows, 937 mapped (25.1%)
- 896 "site" rows, 275 mapped (30.7%)
This year
- 3590 rows, 818 mapped (22.8%)
- 785 "site" rows, 601 mapped (77.3%)

**Comment by damonmcc** [comment]
@fvankrieken is the status on this "In review - Other" now?

**Comment by damonmcc** [comment]
Planning Support is manually mapping projects
