### ISSUE TITLE
compute geographies of CPDB projects during build

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#779]
Downstream use is the Experience Builder app GIS is building and groups who have historically asked the Capital Planning team for a csv of their area's projects

## outcomes
- CPDB build has the tables GIS needs for the new Experience Builder app
- CPDB build has a csv of all projects in each Community District and City Council District (one csv each)

**Comment by damonmcc** [comment]
## current state

At the moment, we categorize all projects as one of the following `Fixed Asset`, `Lump Sum`, or `ITT, Vehicles, and Equipment`. We then treat all `Fixed Asset` projects as if they have a specific location and try to geocode them.

This leaves us with some mapped projects, some unmapped, and many un-mappable by virtue of their exclusion from geocoding.

## potential changes

Some projects do not have a location, some projects involve one or more geographic areas, and some projects involve specific locations. With this is mind, we may want to assign each project a location type like: `Citywide`, `Area`, `Specific`, `Unknown`

All `Citywide` and `Area` projects could be considered mapped. We would then only try to geocode those with a location type of `Specific`.

**Comment by damonmcc** [comment]
the table `cpdb_adminbounds` has 3 columns: `feature_id`, `admin_boundary_type`, `admin_boundary_id`

`feature_id` seems to be Project ID so there are multiple rows per project

**Comment by damonmcc** [comment]
uploaded first attempt at generated csvs to a new EDM Sharepoint folder called [Capital Project's Map](https://nyco365.sharepoint.com/:f:/r/sites/NYCPLANNING/itd/edm/Shared%20Documents/PROJECTS/DATA%20ENGINEERING/DATA%20PRODUCTS/CPDB/Capital%20Projects%20Map?csf=1&web=1&e=Tmu58s)

in `projects_in_geographies_05022024` there are two folders with many csv files: `Community Districts` and `City Council Districts`. In each csv file there should be a row for every capital project which intersect with the geographic area and every column from CPDB for those projects.

**Comment by mbh329** [comment]
@damonmcc Went through a quick pass of the city council data exported in the csv. I viewed a couple files in Excel (City council 1 and 10) and saw that there were some records with indecipherable characters stored in rows. Is this an encoding issue? Or is it just an issue looking at the data in excel as a csv?

Let me know if you see something similar in a different table view 
![description_of_cpe_issue](https://github.com/NYCPlanning/data-engineering/assets/41444592/675b070e-b1c7-4cdb-8383-b7498ae7c7ff)

**Comment by damonmcc** [comment]
@mbh329 I'll take a look!

**Comment by damonmcc** [comment]
@mbh329
looks like reading the csv into Excel creates rows because of a long value in the `geom` column. I found the rows you're looking at and those malformed ones are actually new rows in between real rows

<img width="1190" alt="Screenshot 2024-05-20 at 4 05 27 PM" src="https://github.com/NYCPlanning/data-engineering/assets/7444289/602573a3-f435-4103-a805-9ff62be894c4">

**Comment by damonmcc** [comment]
I've wondered if these csvs should even have a geometry column in them
