### ISSUE TITLE
compile user research for Capital Projects apps

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#782]
Related AE github discussion [here](https://github.com/NYCPlanning/ae-private/discussions/23).

**Comment by jpiacentinidcp** [comment]
User research collected as part of prior investigations into rebuilding CPE are informing some decisions regarding the presentation of capital project data and user interactions associated with viewing and downloading that data. 

Additionally, progress has begun to conduct semi-formal interviews with key user groups and stakeholders to better understand their needs as we work toward the MVP of the Capital Projects Portal. 

Expected interviews should happen within the first have of May, and the findings can inform final design decisions for web and mobile versions of the tool
