### ISSUE TITLE
PLUTO missing some condo lots

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#798]
## summary from GIS

Received email from DOHMH that a few lots are missing from PLUTO 24v1.1. I did some research, they are also missing from 24v1.
 
The condo lots reported missing are:
- 3010987501
- 3010987502
- 3056237502
- 3056237504
- 4019857501 (search 4019850057 for neighboring lot)
- 4019857502 (search 4019850061 for neighboring lot)

I checked several DTMs including 1/26/24 and 2/5/24 versions, since the DTM version listed in the PLUTO readme for 24v1 is listed as 1/31/24. Both DTM versions have base lots where the missing condo lots should be (4019850058 & 4019850059). 
 
My theory is that something is not matching correctly between the base lots in DTM and finding the equivalent condo lot from the Condo table. This is preventing a lot polygon from being generated in MapPLUTO.
 
This should be escalated since we currently have missing lots in the public version and on our internal SDE.

**Comment by fvankrieken** [comment]
resolved in #801
