### ISSUE TITLE
 Opendata: Automate Push -  First Batch

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#800]
Automate and Push the following datasets, in roughly this order:

- [x] Capital Projects Database (CPDB)
  - [x] [commitments](https://data.cityofnewyork.us/City-Government/Capital-Projects-Database-CPDB-Commitments/djxg-kcfi/about_data)
  - [x] [projects](https://data.cityofnewyork.us/City-Government/Capital-Projects-Database-CPDB-Projects/fi59-268w/about_data)
  - [x] [project points](https://data.cityofnewyork.us/City-Government/Capital-Projects-Database-CPDB-Projects-Points-/h2ic-zdws/about_data)
  - [x] [project polygons](https://data.cityofnewyork.us/City-Government/Capital-Projects-Database-CPDB-Projects-Polygons-/9jkp-n57r/about_data)
- [x] LION/Districts Quarterly Release
- [x] Zoning Application Portal (ZAP)
  - [x] [projects](https://data.cityofnewyork.us/City-Government/Zoning-Application-Portal-ZAP-Project-Data/hgx4-8ukb/about_data)
  - [x] [bbls](https://data.cityofnewyork.us/City-Government/Zoning-Application-Portal-ZAP-BBL/2iga-a6mk/about_data)
- [x] Mandatory Inclusionary Housing (MIH)
- [x] E Designations (EDes)

**Comment by alexrichey** [comment]
bumping, so this is at the top of my notifications

**Comment by damonmcc** [comment]
pushed CPDB Commitments via automation. moving on to the 3 Projects datasets

I'm pushing 23adopt first and then will push 24prelim. the columns are the same and it will be informative to see the data change

**Comment by alexrichey** [comment]
thanks @damonmcc - if you can also update the spreadsheet, that'd be cool. Just confirming, for these we need to do two things 
1. Fulfil l our role as OTI and update the old-datasets
2. Time-permitting, create a new dataset to which we can automate the push. 

Sounds like you did #2 for Commitments? Did you also update the old version?

**Comment by damonmcc** [comment]
@alexrichey
the push for [CPDB - Commitments](https://data.cityofnewyork.us/City-Government/Capital-Projects-Database-CPDB-Commitments/djxg-kcfi/about_data) was via automation (CLI) so a new dataset is needed for it right?

**Comment by damonmcc** [comment]
all 4 CPDB pages have the latest version of 24prelim and the [Open Data excel sheet](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/itd/edm/Shared%20Documents/PROJECTS/GIS/Open%20Data/[Open_Data.xlsx](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/itd/edm/Shared%20Documents/PROJECTS/GIS/Open%20Data/Open_Data.xlsx?d=w6735537b8d8e437ab5e53a6b54194b24&csf=1&web=1&e=XjuypJ&nav=MTVfe0Y1RDRCQUIyLTJERTgtNEVGMi1BRTU0LUM4MUFCOUFGMjI5Rn0)?d=w6735537b8d8e437ab5e53a6b54194b24&csf=1&web=1&e=XjuypJ&nav=MTVfe0Y1RDRCQUIyLTJERTgtNEVGMi1BRTU0LUM4MUFCOUFGMjI5Rn0) has been updated

**Comment by damonmcc** [comment]
the 2 ZAP pages have the latest version (20240617) and the [Open Data excel sheet](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/itd/edm/_layouts/15/Doc.aspx?sourcedoc=%7B6735537B-8D8E-437A-B5E5-3A6B54194B24%7D&file=Open_Data.xlsx&action=default&mobileredirect=true) has been updated

**Comment by alexrichey** [comment]
@damonmcc We're just two pesky xlsx attachments away from closing this out.

**Comment by damonmcc** [comment]
🎉
