### ISSUE TITLE
change GFT source data exports

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/data-engineering#816]
to follow-up on #814, two GIS change requests are related to:
1. the columns that are needed for users and EARD to know which dataset value contributed to a question flag
2. the `product/sources` models which are needed for the app to show dataset geometries

met with GIS to confirm the details below

### columns
- level of detail: question flag X source dataset
  - e.g. `natural_resources_forever_wild`, `shadow_nat_resources_forever_wild`, `cats_permit`
- add new columns to the current final table because GFT app needs a single table (~60 columns)

### models
- level of detail: question flag X GFT geometry type
  - e.g. `natural_resources_poly`, `cats_points`, `cats_lots`
  - GFT geometry types are: point, line, lot, poly, buffer
- if geometry type is a buffer, use `ST_UNION` on all the rows
- if there are multiple rows with the same value, use `ST_UNION` to be a single row (e.g. MultiPoint)

**Comment by damonmcc** [comment]
due to changes in #826:
- when a single dataset is used in two flags, we're applying the results of one flag to both

<img width="325" alt="Screenshot 2024-05-24 at 11 27 57 AM" src="https://github.com/NYCPlanning/data-engineering/assets/7444289/85f18d98-7e77-4b8b-a381-459f7b8b4ce9">

**Comment by damonmcc** [comment]
after checkin with GIS and Amanda, source data columns aren't needed for public launch of the app

**Comment by damonmcc** [comment]
data issues found by @jackrosacker after a build using changes from #871 

- [ ] Most (all?) point datasets have pts even after joining to lots
- [ ] Arterial hwy buffers are 90', should be 200'
- [ ] Some buffers are only buffering points, not polys as well
  - Title V buffer
  - State Facility buffer
  - Historic Res Adj buffer
- [ ] Industrial lots buffer is buffering vent towers
- [ ] Vent towers buffer is buffer industrial lots pts
- [ ] Missing sources__historic_resources_polys -> is this the same dataset as the shadows polys fc? The presence of the hist res pt fc suggests that the there should be a dedicated hist res poly fc
- [ ] Source__historic_resources name should have "points" suffix to be consistent -> holding off on re-sourcing this dataset until the name is defined
- [ ] All merged datasets should have variable_type column listing data source for each, in addition to the variable_id column (i.e. datasets like Nat Res, Hist Res, Open Space, etc.)
- [ ] Missing data
  - Shadows hist res
  - Shadows hist res buffer
- [ ] Shadows open space pts -> have never existed in previous releases, is this correct? Matt suggested yes, but having the variable_type column would help with tracking this down

**Comment by croswell81** [comment]
@damonmcc 

I reviewed the [variables.csv](https://github.com/NYCPlanning/data-engineering/blob/main/products/green_fast_track/seeds/variables.csv#L55) and here are my additional comments besides **removing Scenic Landmarks from Historic Shadows**:

**Missing datasets from table**:

- Exposed Railyards
- NYCDOB Tidal Wetland
- NYCDOB Freshwater Wetland
- NYCDOB Coastal Erosion Hazard Area

 
**Missing Filter info in table** (saw other filters listed in this table so included for consistency):

- cats permits filter: status = active or expired) AND (applicationid starts with "PA" OR  "PB")
- arterial hwy filter: source = Appendix H
- DPR Parks Prop filter: CategoryType does not include Cemetery, Lot, Managed Sites, Parkway, Pending, Acquisition, Retired, Strip, Tacking Only, Undeveloped
