### ISSUE TITLE
DE<>GIS Dataset Review Process + Internal Publishing Versions

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#825]
[Related Discussion](https://github.com/NYCPlanning/data-engineering/issues/785)

### Terms
`Build`: outputs of a build process, e.g. files from the build of Pluto

`Draft`: A build that has been promoted to the drafts folder, that is ready for review, and is immutable (ie can't be tinkered with or deleted, except for in rare circumstance). Has a `draft-version`

`Draft Version`: a sequential version, composed of a number and a summary. e.g. 1-initial-build, 2-fix-the-bug

`Published Draft`: a `Draft` moved to `publish` folder after review and approval.

`Published Version`: a sequential number, used in the case of republishing. e.g. 1,2,3. It might make sense to format them as v1, v2, etc.?

### Code Changes Required

- Modify edm-publishing models to account for the `draft-version`. 

- Add DraftVersion functionality to dcpy.utils.versions

- Change builds to output to `edm-publishing / {product-name} / builds / {build-name}`
    Also modify s3 cleanup scripts to clear out the `builds` folder, not the `drafts` folder.

- Add GH Action to `Promote to Draft`. The Action should take in a draft summary (e.g. "fix the bug") and dcpy should infer the next draft number, to create the draft-version. This should also create 'Review Required' GH Issue, and assign to GIS. 

- Modify the Publish GH Action to either publish latest or take a specific draft number. 

- There needs to exist a link between what's in Drafts and what's in `publish`, because those versions might not be identical. E.g. When we publish `draft: 3-fix-the-thing` -> `publish: (v)1` we need to document that pub v1 came from draft 3. [TBD on this one]

- Clean out the drafts folders. No moving data migration required, I don't think... 

### BONUS CODE
- Let's start preparing to kill the `latest` folder. Add an endpoint to qaqc to point to a product latest folder.

**Comment by sf-dcp** [comment]
I have attachment issues with `latest` 🥺

**Comment by fvankrieken** [comment]
One random requirement - `publish` action should definitely not take version as an arg anymore, it should read it from `build_metadata.json`

**Comment by sf-dcp** [comment]
> One random requirement - `publish` action should definitely not take version as an arg anymore, it should read it from `build_metadata.json`

We actually do need a version when publishing with new reorg because the new `draft` folder will look like this: 
`draft/`
* `24v2/`
    *  `1-initial/`
    *  `2-fix-somthing/`
* `24v3`
    *  `1-initial/`

The publish action needs to know where to find the needed draft.

**Comment by sf-dcp** [comment]
@damonmcc @alexrichey @fvankrieken 
Now that new build/draft/publish is on `main`, let's delete unnecessary drafts, migrate existing drafts in review to `build` folders and promote them to `draft` via GHA.  

I think once that's done, this issue can be closed

**Comment by fvankrieken** [comment]
Taking on cbbr, cpdb, and devdb since I'm the one who's been building them!

- [ ] cbbr
- [ ] checkbook (might as well)
- [ ] colp
- [ ] cpdb
- [ ] devdb
- [ ] facdb
- [ ] gft
- [ ] pluto
- [ ] ztl

**Comment by damonmcc** [comment]
^^^^ I'll do checkbook, facdb, gft today

**Comment by damonmcc** [comment]
hesitant to move ZTL files since GIS seems to write to it (`db-zoningtaxlots/draft/main_july_1`)

I can confirm whether they are and coordinate how to handle ZTL

**Comment by fvankrieken** [comment]
Just chatted in person - they definitely do not write to it (and no one should be writing to any of these folders but us)

**Comment by damonmcc** [comment]
migrating COLP files in order to promote the latest draft that passed QA (version `2024-06-11`, branch `ar-build-2024-colp`)

**Comment by damonmcc** [comment]
@sf-dcp I think we've migrated all datasets

**Comment by sf-dcp** [comment]
Opened separate stub issues to implement 1) DE<>GIS Dataset Review Process and 2) GH action to delete builds in s3
