### ISSUE TITLE
PLUTO 24v2

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#831]
### Product Name

pluto

### Build Version

24v2

### Status of Update

- [x] source data extracted
- [x] draft build succeeded
- [x] draft build passed QA
- [x] data packaged and distributed

**Comment by fvankrieken** [comment]
## Data loading

### Manual Updates

#### Updated 2x a year typically in June and December
- [ ] **dcp_colp** (check [here](https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-colp.page)) 
#### Currently updated with each new release of a major version of PLUTO - important to make sure this is up to date
- [ ] **pluto_corrections** (pulling from bytes, must update when there's updates to **pluto_input_research**)

### Automated Updates

#### Open data automated pull

> Check [here](https://github.com/NYCPlanning/db-data-library/actions/workflows/open-data.yml) to see the latest run

- [ ] **dsny_frequencies**
- [ ] **dpr_greenthumb**
- [ ] **lpc_historic_districts**
- [ ] **lpc_landmarks**

#### DOF Automated Pull and Number of Buildings

- [ ] **pluto_pts** (Check [here](https://github.com/NYCPlanning/data-engineering/actions/workflows/pluto_input_pts.yml))
- [ ] **pluto_input_geocodes** (Check [here](https://github.com/NYCPlanning/data-engineering/actions/workflows/pluto_input_pts.yml))
- [ ] **pluto_input_cama_dof** (Check [here](https://github.com/NYCPlanning/data-engineering/actions/workflows/pluto_input_cama.yml))
- [ ] **pluto_input_numbldgs** (Check [here](https://github.com/NYCPlanning/data-engineering/actions/workflows/pluto_input_numbldgs.yml))

### Updated with Quarterly updates (check [here](https://github.com/NYCPlanning/db-data-library/actions/workflows/quaterly-updates.yml))

- [ ] **dcp_cdboundaries_wi**
- [ ] **dcp_ct2010**
- [ ] **dcp_cb2010**
- [ ] **dcp_ct2020**
- [ ] **dcp_cb2020**
- [ ] **dcp_school_districts**  
- [ ] **dcp_councildistricts_wi**  
- [ ] **dcp_firecompanies**  
- [ ] **dcp_policeprecincts**
- [ ] **dcp_healthareas**  
- [ ] **dcp_healthcenters**

### Updated with Zoning Taxlots 

(check [here](https://github.com/NYCPlanning/data-engineering/actions/workflows/zoningtaxlots_dataloading.yml) for latest run).

These are all produced by GIS, who typically update them sometime in the first week of each month.
Check in with them before archiving with data library

- [ ] **dof_dtm**
- [ ] **dof_shoreline**
- [ ] **dof_condo**
- [ ] **dcp_commercialoverlay**
- [ ] **dcp_limitedheight**
- [ ] **dcp_zoningdistricts**
- [ ] **dcp_specialpurpose**
- [ ] **dcp_specialpurposesubdistricts**
- [ ] **dcp_zoningmapamendments**
- [ ] **dcp_edesignation**

### Never Updated (Safe to ignore)

- [x] **doitt_zipcodeboundaries** (almost never updated, check [here](https://data.cityofnewyork.us/Business/Zip-Code-Boundaries/i8iw-xf4u))
- [x] **fema_firms2007_100yr**
- [x] **fema_pfirms2015_100yr**
- [x] **dcp_zoningmapindex**

**Comment by fvankrieken** [comment]
Depends on #657 as well

**Comment by fvankrieken** [comment]
Copying in notes from @croswell81's 5/14 email on QA. My notes in bold

### Mismatch
Zoning fields
- zero changes in ZD3 and ZD4, both for 24v2-24v1.1 and 24v1.1-24v1. Might want to check that this is being calculated correctly. **I think this is fine. Only 215 records have zd3, only 13 have zd4, so it makes sense that we'd see little change**

Geo
- <200 record changes for council districts. **Again, I think this is fine - PLUTO 24v1 used 23d which had updated council districts (and 120k+ changed records from 23v3**

### Aggregate graph
Over 15% loss in factory area reported. LS's notes say to ignore this, but worth poking around slightly

### Outlier tables
- Unreasonable increase in building area 5009550025, 5040430087, 3010530039, 2048350012, 3060500015 all had 500%+ increase. Last four could be correcting to actual value, first one seems way off, all should be checked
- unreasonably small apartments: all non-NYCHA records should be looked into
- blgdarea/lotarea > numfloors*2
  - 3027017502 Looks like lot area is wrong
  - 3023677503 and floors may be wrong
  - 3018770027 part of building has 2 floors, part has 7. Numfloor issue?
  - 3001510009 can't tell if one floor or partially 2

### Other observations
- 150 ZD1 values went to Null

**Comment by fvankrieken** [comment]
### Null ZD1 Values

about half of these seem to be records that aren't in DTM, but are still in PTS. I think these are largely fine to leave.

The 70 that are in DTM are more troubling. 

Spot checking one, dtm and pts seem to view it as a non-condo lot. However, it has a record in dof_condo that treats it as a condo lot with a primebbl. Because of this, pluto logic attempts to use its primebbl for geospatial data, but there is none - this primebbl is not in dtm. Both are in PTS though. So it seems we have two lots, one condo and one not, that are "the same" lot maybe.
- we have two lots: 1004577502 (311 Bowery) and 1004570001 (3 Extra Place)
- in PTS, 1004577502 is a primebbl with 2 corresponding unit bbls. 1004570001 is a "normal" non-condo bbl that does not get geocoded
- in DTM, 1004577502 is not found, while 1004570001 has the geom that seems to be associated with these two addresses
- in dof_condo, we have one row linking base_bbl 1004570001 to primebbl 1004577502

So dof_condo data seems to be in line with nothing, dtm thinks that we only have this non-condo bbl, and pts says we have both a condo primebbl and a noncondo bbl at this location

**Comment by fvankrieken** [comment]
cont
- [ ] 2023690008, 2023690009, 2023690010 - one building spanning 3 lots. 218 res, 219 total for each. Currently vacant lot, so correct all to zero?
- [ ] 4096207501 - according to hpd online, 32 class a units and 127 b. Maybe fine - need to see how we handle hotels
- [ ] 1007677506 - usual condo mishap. 170, 169 to 14, 13
- [ ] 3041047501 - see above. 244, 144 to 22, 12
- [ ] 1018700045 - almost all class b, maybe fine
- [ ] 1020580001 - class b
- [ ] 3010057502 - class b
- [ ] 1012530010 - class b
- [ ] 1003737501 - classic condo. 121, 121 to 11, 11
- [ ] 3055167504 - classic condo. 121, 121 to 11, 11
- [ ] 2033310053 - vacant lot, 117, 116 units currently. Under construction

**Comment by fvankrieken** [comment]
### Increase in ~bldg~ lotarea
- [ ] 5009550025 - correct from 732550000 (almost half of staten island!) to 75620
- [ ] 3004380001 - seems fine
- [ ] 4117610011 - seems fine
- [ ] 5040430087 - seems fine
- [ ] 2023690069 - seems fine
- [ ] 3010530039 - seems fine
- [ ] 2048350012 - seems fine
- [ ] 1007350035 - seems fine
- [ ] 3060500015 - seems fine

**Comment by fvankrieken** [comment]
@AmandaDoyle - a bunch of details above, but this is a bit of a summary of my qa, formatted around the sections of @croswell81's email

# Mismatch
Zoning fields
- zero changes in ZD3 and ZD4, both for 24v2-24v1.1 and 24v1.1-24v1. I think this is fine. Only 215 records have zd3, only 13 have zd4, so it makes sense that we'd see little change

Geo
- <200 record changes for council districts. Again, I think this is fine - PLUTO 24v1 used 23d which had updated council districts (and 120k+ changed records from 23v3

# Aggregate graph
Over 15% loss in factory area reported. LS's notes say to ignore this, but worth poking around?

# Outlier tables

## increase in building area
Very important note - this check is called "unreasonable increase in building area" but actually checks _lot_ area (see [here](https://github.com/NYCPlanning/data-engineering/blob/9bc13065c0b9e4476a5afe4356675590a326ba81/products/pluto/pluto_build/sql/qaqc_outlier.sql#L21)). We could modify this to actually look at building area, or both (I talk about this a bit in #854). I imagine we do actually want to be looking 

I've corrected the one lot that PTS says occupies roughly half of SI now. The rest seem to all be changes from unreasonably small values to very reasonable values, so no action needed.

## blgdarea/lotarea > numfloors*2
I looked into these - they all seem largely fine - cases where there's active construction/demolition and number of floors seems to have gone down or up without correcting building area. If worth correcting, I can work on that

## unreasonably small apartments
I've been doing a lot of manual corrections here, and in the process have had a few odd cases where I could use advice
- single new building spanning 4 lots. Seems like dtm is just not quite up-to-date here, as the building seems completed (bbls 2023510001, 2023510003, 2023510012, 2023510020. "Estela" apartments). Each lot has the units of the whole building. Tough one to fix on our end
- class b units - many of these cases seem to have sq footage of 200-300 and are mostly class b units, but not NYCHA owned. Some are hotels, some are unclear. Are these fine? 
  - For the hotel ones specifically - are hotel units supposed to be represented as res units in PLUTO?
- there are a couple vacant lots with planned construction that have their proposed units, sq footage, etc in PTS already for some reason. Should we correct all relevant fields (of fields that we currently correct) to zero? 
- one record where sq footage seems way off, but can't find a solid number to use. Do we correct, or just leave?

# Null ZD1 Values

about half of these seem to be records that aren't in DTM, but are still in PTS. I think these are largely fine to leave.

The 70 that are in DTM (but still are not getting assigned geoms) are more troubling. 

Spot checking one, dtm and pts seem to view it as a non-condo lot. However, it has a record in dof_condo that treats it as a condo lot with a primebbl. Because of this, pluto logic attempts to use its primebbl for geospatial data, but there is none - this primebbl is not in dtm. Both are in PTS though. So it seems we have two lots, one condo and one not, that are "the same" lot maybe.
- we have two lots: 1004577502 (311 Bowery) and 1004570001 (3 Extra Place)
- in PTS, 1004577502 is a primebbl with 2 corresponding unit bbls. 1004570001 is a "normal" non-condo bbl that does not get geocoded, and does not have 1004577502 as its primebbl
- in DTM, 1004577502 is not found, while 1004570001 has the geom that seems to be associated with these two addresses
- in dof_condo, we have one row linking base_bbl 1004570001 to primebbl 1004577502

So thinks that we only have this non-condo bbl, pts says we have both a condo primebbl and a noncondo bbl at this location, and dof_condo says that the non-condo bbl actually does belong to our condo primebbl. So none of them agree

The overall figure of 150 bbls losing ZD1 doesn't seem entirely unusual, we had something similar for 23v3-24v1. But it's not great how out of sync these are. We could try using a more recent pts now that its been updated a few more time since this build, but then that might throw other things out of whack and start over this review to some extent.

# Other notes
I pinged you about another odd edge case - 3047927502 only doesn't have a primary row in pts, only this non-condo bbl (3047920029) (condo_number is null). So it's blank in [zola](https://zola.planning.nyc.gov/l/lot/3/4792/29). Don't think there's anything really to do but it's an odd one

**Comment by AmandaDoyle** [comment]
Triaging my reply
- **Mismatch and Aggregate graph** changes are fine and do not need to be investigated.

**Outlier tables**

increase in building area - sounds good

For blgdarea/lotarea > numfloors*2 - I looked into the 4 records where new value = 'true' in the QAQC report and these may be worth correcting.  I think we've addressed these by updating the number of floors.

For unreasonably small apartments
- For the one record where sq footage seems way off - can you give me the BBL?
- For the vacant lots with planned construction - if run the query 
```
SELECT * FROM fvk_pluto_corrections.pluto where landuse = '11' and unitstotal::numeric > 0;
```
I get 8 lots.  After skimming through these records I would leave them as is.  The unit totals are not that large.  The unit counts and building classes are out of sync on DOF's side.

- For class b units, what class b units units are you referring to?  PLUTO does not have class b units units.  DOF classifies residential units as the following:
Hotels/motels, nursing homes and SROs do not have residential units, but boarding
houses do. Basement units for building superintendents are counted as a residential
unit.
^ this is from the PLUTO data dictionary.
- For the single new building spanning 4 lots the best that we can do is divide the real number of units equally between the 4 tax lots

Null ZD1 Values
It is concerning that DOF's data is so out of sync.  I tried to parse through this and the one question I kept coming back to was if we were to pull in a more up to date DTM and condo tabe (i.e. from yesterday) would this help solve some of these problems?  

When we talk about PLUTO QAQC on Thursday I will also call out things that we can pull out to report back to DOF.

Thanks for diving into PLUTO.

**Comment by fvankrieken** [comment]
A couple notes 

## Null ZD1
I ran a new build with updated PTS. Overall counts look very similar, and there are more rows that lost certain geocoding fields. I think we stick with what we have, sadly

## Unreasonably small apartments
- class b units -> there are several lots that when I look up their buildings in hpdonline have almost exclusively classb units, yet pts seems to have all of these counted. I can produce more of a little report of these
- for the vacant lots - these are not marked as vacant lots, pts seems to think they're completed buildings. But looking them up shows that they are in fact vacant or incomplete. See 3024570034 and trio of 3020580049 , 3020580047, 3020580050. The latter seem to have a planned hotel on the site

**Comment by fvankrieken** [comment]
Decisions from 6/5 chat with @AmandaDoyle

- vacant lot showing up as buildings
  - correct to zero units, don't correct other fields
  - contact DOF with list of identified bbls
- class b units showing up as condo units
  - don't correct
  - contact DOF with list of bbls, clarify if their categorization of units in PTS has changed

**Comment by fvankrieken** [comment]
Summary for post-qa/corrections @croswell81

Copying in notes from @croswell81's 5/14 email on QA. My notes in bold

### Mismatch
Zoning fields
- zero changes in ZD3 and ZD4, both for 24v2-24v1.1 and 24v1.1-24v1. This is fine, there are very few rows with non-null zd3 or 4

Geo
- <200 record changes for council districts. This is fine - 24v1 had the big change in council districts

### Aggregate graph
Over 15% loss in factory area reported. We are not doing anything here

### Outlier tables
- Unreasonable increase in ~building~lot area. This check is not named properly. Most of these are going from an incorrect value to correct value. All set here
- unreasonably small apartments: most records corrected. There were a few odd cases
  - many bbls which seem to have classb units reported as res units. We're not correcting, but will contact DOF to see if this is in error or if their classification for PTS res units has changed to include SROs or other similar units
  - there are a few rows where there are vacant lots with plans for building that are showing up in PTS as actual buildings. In multiple cases, there are three lots (that seem like they will be merged later) that each have the total number of planned units under res units. We're correcting res/total units to 0, leaving area fields, and contacting DOF about the issue
- blgdarea/lotarea > numfloors*2. These have been corrected

### Other observations
- 150 ZD1 values went to Null. This seems to be "usual" weirdness of PTS/DTM not aligning to some degree (and therefore lots not having geoms), and is in line with the usual amount of lots that lose geom from one major to another

**Comment by croswell81** [comment]
@fvankrieken confirming the QA should be run on 

version = Draft
build = fvk-pluto-corrections
report type = compare w/ previous version

**Comment by fvankrieken** [comment]
Yup!

**Comment by damonmcc** [comment]
24v2 is on Bytes, Open Data has 24v1.1

@fvankrieken anything blocking us from distributing to Open Data?

**Comment by fvankrieken** [comment]
Nope!

**Comment by damonmcc** [comment]
@alexrichey is working on distributing to Open Data

**Comment by alexrichey** [comment]
Distributed All the PLUTO files. Will go ahead and close this out.
