### ISSUE TITLE
COLP 2024-06

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#858]
# COLP Source Data Updates

Like most of our data products, source data must be updated in data library before COLP is run/built.

All source data listed is to be uploaded as .sql files.

### Bytes of the Big Apple Source Data
Make sure versions of each dataset are the most recent published version in DigitalOcean.

- [x] dcp_pluto - https://www.nyc.gov/site/planning/data-maps/open-data.page#pluto (Version that was last built and published, typically updated 4x a year)
- [x] dcp_colp - https://www.nyc.gov/site/planning/data-maps/open-data.page#city_facilities (Version that was last built and published)
- [x] dcp_boroboundaries_wi - https://www.nyc.gov/site/planning/data-maps/open-data/districts-download-metadata.page (New release with every geosupport but should not change from version to version)

### Manual Uploads
- [x] dcas_ipis - DCAS emails us a csv and this is ingested manually

### Recieved via GIS Team uploaded to DO

- [x] dof_air_rights_lots

### AR Notes

@AmandaDoyle and I met with DCAS last week, and they're aware of the data that they need to send us for this update. My minimal notes:

- Gazetteer - they're kicking this off now
- Timeline: they reach out to agencies around June, get records around July-Sept, early Oct complete IPIS, resubmit to DCP. (use charter says Nov as final date)
- DCP's Nov COLP update to have gazetteer. No schema changes.

- This COLP update will have new use type categories for parking

**Comment by alexrichey** [comment]
Current status: waiting for DCAS to send us data.

**Comment by alexrichey** [comment]
BUILD [here](https://cloud.digitalocean.com/spaces/edm-publishing?path=db-colp%2Fdraft%2Far-build-2024-colp%2F)
branch: `ar-build-2024-colp`

**Comment by caseysmithpgh** [comment]
Morning @alexrichey 

We finished COLP QA, apologies for the delay. We have two notable flags and some normalization notes for future builds. 

- **Flags**: usetype changes include +1 Jail and +1 Courthouse. This is pretty abnormal, can you confirm the accuracy before we move forward with publishing?
- Normalization notes for Ipis_modified_names (parcel vs display_name)
  - PS and P.S.
  - IS and I.S. 
  - BRONX CHARTER SCH FOR BETTER LRN -> School and Learn?  
  - Engine # vs FDNY Engine # 
    - Primary_use_text field FDNY VS NYPD

cc @croswell81 @jackrosacker

**Comment by fvankrieken** [comment]
@damonmcc we don't have the schema in the build db anymore, so I'm going to [repeat this draft build](https://github.com/NYCPlanning/data-engineering/actions/runs/9908831678) on `main` just to look at the intermediates

**Comment by fvankrieken** [comment]
The new courthouse is interesting. It shows up as this
- bbl: 4096570001	
- 126-02 82 AVENUE
- parcelname: QUEENS CRIMINAL COURT/PARKING LOT

It's part of a complex with queens borough hall (one block, two bbls), which does have an existing row under "COURTHOUSE"
<img width="761" alt="image" src="https://github.com/user-attachments/assets/d1faf888-95ed-489a-8ffb-1a4315f4be7c">

This BBL is new to COLP, though it is the actual courthouse
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/a5496830-7e23-4262-b592-a62dde3ca551">

Existing row (in past colps and new colp) is for borough hall
- bbl: 4022740002.00000000
- 120-55 QUEENS BOULEVARD
- parcelname: QUEENS BOROUGH HALL

<img width="1097" alt="image" src="https://github.com/user-attachments/assets/80ee0925-41cd-47a9-b7af-32a067a59ee3">

So the new row seems correct, and if anything it maybe seems that this old row shouldn't be classified as "COURTHOUSE" if it's really the borough hall and courthouse is nextdoor. Maybe lot was split at some point?

**Comment by damonmcc** [comment]
@fvankrieken a lot splitting seems right. maybe in the previous COLP we could look at that spot (either the final table or the version of PLUTo that went into it) and see how many lots were there?

**Comment by fvankrieken** [comment]
The same lot is the "new" jail - it seems there is a jail on the site. Not sure why there was no record for it before.

**Comment by croswell81** [comment]
@fvankrieken / @damonmcc: Since Amanda is out for a few days, could you reach out to your contact for the jails and courthouse data sources to confirm they agree with the change? Once we have that confirmation I believe we can publish.

**Comment by damonmcc** [comment]
@croswell81 we're gonna writeup the details on the source data that's going into the jail/courthouse usetype changes

so that when we reach out, it'll be easy to ask for confirmation on what's changed

**Comment by croswell81** [comment]
@damonmcc thank you for the clear explanation. For my understanding, is our policy to create a record (row) for each individual use (i.e., muni. parking - indoor, agency office, borough office, courthouse, custodial, and jail would each be a unique record)?

**Comment by damonmcc** [comment]
@croswell81 yes and there seem to be a few more things that contribute to "what is a unique row":
- `AGENCY`, so there could be two rows where only that value differs
- `LEASED `, so there could be two rows where only that value differs
- I think there are duplicate rows
  - e.g. where `BBL=1001530001 AND AGENCY=BLDGS AND LEASED=L` returns 2 rows

**Comment by croswell81** [comment]
@damonmcc we should discuss next steps tomorrow, 7/23

**Comment by damonmcc** [comment]
DCAS confirmed via email on 8/1 that the following two records have jail uses:
- bbl = 4096570001, parcel_name = "QNS CRIMINAL COURT/PARKING LOT"
- bbl = 2027800073, parcel_name = "NEW FULTON FISH MARKET"

**Comment by caseysmithpgh** [comment]
Thanks @damonmcc!!

Does this mean GIS team is clear to proceed on publishing colp?

**Comment by damonmcc** [comment]
@alexrichey should DE run the [publish action](https://github.com/NYCPlanning/data-engineering/actions/workflows/publish.yml) and then distribute to Open Data?

**Comment by alexrichey** [comment]
@damonmcc Yeah, but we gotta assemble the package and put it on DO. I'll be going through Open Data publications this week, and can take care of it

**Comment by croswell81** [comment]
@damonmcc & @alexrichey: GIS team will need to distribute to SDE and webteam so let us know when the package is ready.

cc: @caseysmithpgh @jackrosacker

**Comment by damonmcc** [comment]
@caseysmithpgh 

I promoted the build so it's now in `edm-publishing/db-colp/publish` as 2024-06-01` and `latest`

![Screenshot 2024-08-07 at 12 13 20 PM](https://github.com/user-attachments/assets/c920b937-da9e-438d-b5c2-8fffecd30f0e)

**Comment by damonmcc** [comment]
@croswell81 

> GIS team will need to distribute to SDE and webteam so let us know when the package is ready.

It's my understanding that the current process for COLP is:
1. GIS packages
2. GIS distributes to SDE and webteam
3. DE distributes to Open Data

cc @alexrichey @caseysmithpgh

**Comment by croswell81** [comment]
@damonmcc Thank you clarifying the process. I was confused from the "Yeah, but we gotta assemble the package and put it on DO" comment earlier. For further clarity, what source do you use to publish to Open Data portal?

@caseysmithpgh will be running our scripts to package and publish on our end.

**Comment by damonmcc** [comment]
@croswell81 at the moment, DE uses the files from Bytes. so we won't publish to Open Data until webteam updates Bytes

**Comment by damonmcc** [comment]
@caseysmithpgh I'm down to review it

**Comment by caseysmithpgh** [comment]
Sweet, I'll move ahead with publishing then. Likely wont be on bytes until Monday

**Comment by damonmcc** [comment]
It's on bytes and has been archived via data library (for use in FacDB 24v2)

**Comment by alexrichey** [comment]
This has been distributed. Closing out!
