### ISSUE TITLE
PLUTO - zoning data correction

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/data-engineering#92]
For tax lot 4158620001 add in MX-21 for the Special District and M1-4/R6 for the zoning 2 district.  This should be done before 23v2.1.  

DE should investigate how to adjust the thresholds for assigning these so that a manual correction is not needed, if it's possible to do so without having negative impacts elsewhere.

**Comment by damonmcc** [comment]
re-opening to use this issue for a change / enhancement to the thresholds
