### ISSUE TITLE
"Odd lots" - ZTL QA follow-up

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/data-engineering#921]
ZTL QA is finished, and has passed, but I'm flagging two lots that appeared in the qc_bbldiff file that should plausibly have been caught by an earlier build. 

| BBL | Image |
|--------|--------|
| 3075760012 | ![image](https://github.com/NYCPlanning/data-engineering/assets/18175209/39b98336-0aac-4d23-9d86-a43f887dd97c)|
| 4089250001| ![image](https://github.com/NYCPlanning/data-engineering/assets/18175209/33f17f10-2c4d-4f16-b7a7-ea494b44f16d)| 

Note that both seem to be improvements, but since they are correcting on errors that appear to have persisted in previous versions without being picked up by either the ZTL build or the QA process, flagging for further review.

bblnew | zd1new | zd2new | zd1prev | zd2prev
-- | -- | -- | -- | --
3075760012 | R6 |   | R6 | C8-2
4089250001 | R6A | R3-1 | R6A |

**Comment by fvankrieken** [comment]
Can you clarify what you mean by "caught"? What was the issue with these lots?

**Comment by jackrosacker** [comment]
For both, the extent of the zoning files didn't change, but the zoning values on the lots did. The second lot at least intersects with both relevant zoning districts, while the first doesn't intersect at all with the old zd2 district.

In the image, the pink indicates the qc bbldiff lot. The orange lines/labels indicate the current nyzd file, and the green lines/labels indicate the prior nyzd file. 

I'll add a snippet of the attribute table to the initial comment.

**Comment by fvankrieken** [comment]
Gotcha.

At least with the first, looks like a real change? Looking at zola, it's clearly partially in a C8-2
<img width="1003" alt="image" src="https://github.com/NYCPlanning/data-engineering/assets/9454672/a026f29a-5ad8-49d9-9190-d76d25314783">

**Comment by jackrosacker** [comment]
According to the DTMs we have archived, it looks like the first lot split between the 3/29 and 4/5 versions, while this current QA should be comparing between the DTM from the current build (6/4) and the DTM from the prior build (5/3).

It looks like an error is being corrected, but it's odd that it's popping up now and not earlier in the Spring.

**Comment by jackrosacker** [comment]
@fvankrieken I was looking for an unrelated issue and noticed this one from a while back. I think that this can be closed as it is likely either (1) specific to an old version of ZTL and no longer current, or (2) has been resolved by the recent improvements to how ZTL comparisons are made during the QA diff process.

**Comment by fvankrieken** [comment]
Sounds good
