### ISSUE TITLE
DBT ZTL: Simplify DAG for first-draft implementation

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#924]
Follow up to #911 . After initial flow chart/DAG is made, we should attempt to simplify it, grouping steps as needed to create a simple, relatively atomic DAG to create ZTL. #911 has some brief description of what this might look like, but it's very dependent on what the initial DAG ends up looking like, so this description will remain a bit of a stub at the moment

This should also include deciding on initial "grouping" of models. `stg`, `int`, `product` as well as any "sub-groupings" (like `int_flags` in gft). GFT is a good example but also has a lot of assumed knowledge there. This [wiki page](https://github.com/NYCPlanning/data-engineering/wiki/Code-Conventions#model-foldersfile-structure) has good guidance (as well as links to dbt's official guidance)

**Comment by HengJiang0206** [comment]
```mermaid 
flowchart 
dcp_commercialoverlay_0--preprocessing--> dcp_commercialoverlay_1
dcp_limitedheight_0 --preprocessing --> dcp_limitedheight_1
dcp_specialpurposesubdistricts_0 -- preprocessing --> dcp_specialpurposesubdistricts_1
dof_dtm_0--preprocessing------->dof_dtm_1
dof_dtm_1---->dof_dtm_2
dcp_specialpurpose_0 --preprocessing --> dcp_specialpurpose_1
dcp_zoningdistricts_0 --preprocessing --> dcp_zoningdistricts_1
dcp_zoningmapamendments_0 --preprocessing --> dcp_zoningmapamendments_1
dcp_zoningmapindex_0 --preprocessing --> dcp_zoningmapindex_1
dof_dtm_1---->dcp_zoningmapamendments_2
dcp_zoningmapamendments_1---->dcp_zoningmapamendments_2
dof_dtm_1---->dcp_zoningmapamendments_3
dcp_zoningmapamendments_1--->dcp_zoningmapamendments_3
dof_dtm_2---->dcp_zoningmapindex_2
dcp_zoningmapindex_1---->dcp_zoningmapindex_2
dcp_zoningmapindex_2---->dcp_zoningmapindex_3
dof_dtm_2---->dcp_limitedheight_2
dcp_limitedheight_1---->dcp_limitedheight_2
dcp_limitedheight_2---->dcp_limitedheight_3
dof_dtm_2---->dcp_specialpurpose_2
dcp_specialpurpose_1---->dcp_specialpurpose_2
dcp_specialpurpose_2---->dcp_specialpurpose_3
dof_dtm_2---->dcp_commercialoverlay_2
dcp_commercialoverlay_1---->dcp_commercialoverlay_2
dcp_commercialoverlay_2---->dcp_commercialoverlay_3
dcp_zoning_taxlot_0---->dcp_zoning_taxlot_1
dcp_zoning_taxlot_1---->dcp_zoning_taxlot_2
dof_dtm_1---->dcp_zoning_taxlot_2
dcp_zoningdistricts_1---->dcp_zoningdistricts_2
dof_dtm_2---->dcp_zoningdistricts_2
dcp_zoningdistricts_2---->dcp_zoningdistricts_3
dcp_zoningdistricts_3---->dcp_zoningdistricts_4
zone_dist_priority_0---->zone_dist_priority_1
zone_dist_priority_1---->dcp_zoningdistricts_5
dcp_zoningdistricts_4---->dcp_zoningdistricts_5
dcp_zoningdistricts_5---->dcp_zoningdistricts_6
dcp_zoningdistricts_3---->dcp_zoningdistricts_6
dcp_zoningdistricts_6---->dcp_zoning_taxlot_3
dcp_zoning_taxlot_2---->dcp_zoning_taxlot_3
dcp_zoning_taxlot_3----> dcp_zoning_taxlot_4
dcp_commercialoverlay_3----> dcp_zoning_taxlot_4
dcp_zoning_taxlot_4----> dcp_zoning_taxlot_5
dcp_specialpurpose_3---->dcp_zoning_taxlot_5
dcp_zoning_taxlot_5---->dcp_zoning_taxlot_6
dcp_limitedheight_3---->dcp_zoning_taxlot_6
dcp_zoning_taxlot_6---->dcp_zoning_taxlot_7
dcp_zoningmapindex_3---->dcp_zoning_taxlot_7
dcp_zoning_taxlot_7---->dcp_zoning_taxlot_8
dcp_zoningmapamendments_3---->dcp_zoning_taxlot_8
dcp_zoning_taxlot_8---->dcp_zoning_taxlot_9
dcp_zoning_taxlot_9---->dcp_zoning_taxlot_10
dcp_zoningmapamendments_2---->dcp_zoning_taxlot_10
dcp_zoning_taxlot_10---->dcp_zoning_taxlot_11

```
```

**Comment by fvankrieken** [comment]
This is a great first effort!

So we'll chat about this later today and probably also Monday, but I think when it comes to dcp_zoning_taxlot we're going to approach it very differently. This is certainly an idealized version (from the DAG's perspective) of what this could look like, but I think we'll want to aim for something along these lines.

```mermaid 
flowchart LR
stg__dof_dtm---->int__zoningmapamendments
stg__dcp_zoningmapamendments---->int__zoningmapamendments
stg__dof_dtm---->int__zoningmapindex
stg__dcp_zoningmapindex---->int__zoningmapindex
stg__dof_dtm---->int__dcp_limitedheight
stg__dcp_limitedheight---->int__limitedheight
stg__dof_dtm---->int__specialpurpose
stg__dcp_specialpurpose---->int__specialpurpose
stg__dof_dtm---->int__commercialoverlay
stg__dcp_commercialoverlay---->int__commercialoverlay
stg__dof_dtm---->int__zoning_taxlot
stg__dcp_zoningdistricts---->int__zoningdistricts
stg__dof_dtm---->int__zoningdistricts
seed_zone_dist_priority---->int__zoningdistricts
int__zoningdistricts---->dcp_zoning_taxlot
int__commercialoverlay----> dcp_zoning_taxlot
int__specialpurpose---->dcp_zoning_taxlot
int__limitedheight---->dcp_zoning_taxlot
int__zoningmapindex---->dcp_zoning_taxlot
int__zoningmapamendments---->dcp_zoning_taxlot
int__zoningmapamendments---->dcp_zoning_taxlot
```

This is obviously a bit idealized. I think what will make sense moving forward will be taking each of these "int" tables and trying to implement them one at a time. For each, see if it can truly be a single model, or if we will need multiple intermediates like in both the current code and in your flowchart - it's quite possible. And then, once each of them are implemented, work on creating the final table. 

So for #925, process will look like
- implement staging tables (merge to main)
- implement "target" int tables (the highest number of each one in your flow chart) one at a time, starting with zonedist. These tables can maybe stay long format, we'll chat about this. I'd say we merge the first one to main, then maybe the rest are done in a single PR
- implement `dcp_zoning_taxlot`/`dcp_zoning_taxlot_export`

**Comment by fvankrieken** [comment]
And I'm not providing this flowchart as a "right answer" to the issue here - it really is an idealized version that's not really taking into account the complexity in the queries (and optimizing for performance, etc). In #911, you made something that represented reality, and in this issue, you've made something trying to simplify what actually exists, whereas what I made is something that's a bit more naive. I think these probably have us in a good spot of trying to implement, and we'll likely end up somewhere in between
