### ISSUE TITLE
DBT ZTL: Refine initial DAG, models

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/data-engineering#928]
After we have a working dag/dbt project from #925, it'd be good to evaluate our DAG/sql and iterate on our models. Did we compress too much and now have queries that are too busy and hard to read? Or are some models maybe too discrete, and could be grouped further? This can be a bit of a gray area, but to me it comes down to largely
  - how readable is the DAG that dbt generates?
  - using that DAG as a reference, how intuitive is it to read through the repo and figure out what the transformations are doing?

There's also likely a macro to be written. The code for all the "per area" files/models is very repetitive and likely could have some of it pulled out

**Comment by fvankrieken** [comment]
So there are a few parts to this.
- [ ] simplify staging models. I think this will be pretty minimal, but we should glance over and see if there are simple changes to make - do two consecutive CTEs do very little differently, and could we combine them? Stuff along those lines
- [ ] simplify intermediate models. This has a few parts
  - move logic from "dcp_zoningtaxlots" table upstream. There's a bunch of logic relating to some final filtering, altering etc that ideally could happen upstream from this final join table. 
  - Simplify/clean existing code in intermediate models. Evaluate final columns selected - are these used downstream? Are these helpful as persisted intermediate columns for debugging?
  - Edit constraints/tests. Ideally we want to be as constraining as possible here (unique set of columns ideally is just 2 columns)

**Comment by HengJiang0206** [comment]
Todos:

- [ ] Move `commercialoverlay` pivoting logic upstream
- [ ] Move `limitedheightdistrict` column setup upstream
- [ ] Move `zoningmapnumber` column setup upstream 
- [ ] Move `zoningmapcode` column setup upstream
- [ ] Move `zoningdistricts` pivoting logic upstream
- [ ] Create a macro for setting nulls  for parks
- [ ] Move `commercialoverlay` drop duplicate logic upstream
- [ ] Create per area macro
