### ISSUE TITLE
Opendata: Automate Push - Second Batch

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#938]
May Open Data (Automate and Distribute)
- [x] POPS (Sasha)
- [x] ZTL (Damon)
- [x] Zoning - NYC Georeferenced Zoning Maps
- [ ] Zoning - NYC GIS Zoning Features
- [x] Finish LION Automations (5 total)
  - Push XLSX attachments
  - File-Only Datasets, e.g. PAD

Other (Just Automate, don't distribute)

- [ ] Housing DB (Finn - 8 total)

***

👆 This would get us to approx 80% done, meeting our quarterly goal.

**Comment by fvankrieken** [comment]
I'll take housing!

**Comment by alexrichey** [comment]
@sf-dcp Do you want to take POPs? Looking at it, and it's fairly straightforward.

**Comment by damonmcc** [comment]
I'll do ZTL

**Comment by alexrichey** [comment]
> I'll take housing!
> 
> @alexrichey housing actually seems up-to-date in bytes, I might wait until we get 24Q2 built to actually package and get things pushed. But metadata files at least have been made

@fvankrieken Gotcha. Are the metadata files checked in somewhere?

**Comment by damonmcc** [comment]
ZTL 202405 action run [here](https://github.com/NYCPlanning/data-engineering/actions/runs/9812572118) and Open Data page is updated

updated [the excel sheet](https://nyco365.sharepoint.com/:x:/r/sites/NYCPLANNING/itd/edm/_layouts/15/Doc.aspx?sourcedoc=%7B6735537B-8D8E-437A-B5E5-3A6B54194B24%7D&file=Open_Data.xlsx&action=default&mobileredirect=true) to show ZTL is up-to-date on Open Data

<img width="400" alt="Screenshot 2024-07-05 at 3 05 52 PM" src="https://github.com/NYCPlanning/data-engineering/assets/7444289/e2a88546-d79a-42ba-8a36-68631dc57a36">

**Comment by sf-dcp** [comment]
I also published POPs to Open Data and updated the excel spreadsheet. @alexrichey, could you please double check if the sheet edits look good?

**Comment by alexrichey** [comment]
@sf-dcp yep! looks good. There's one more POPs dataset that we need to push manually, which we can do on Monday

**Comment by alexrichey** [comment]
Closing out. There's one hiccup: `NYC GIS Zoning Features: shapefile` needs to be updated by some script that OTI has, which goes layer-by-layer. @croswell81 is going to request that they update that in the meantime. (til we automate the 6 datasets in the product)
