### ISSUE TITLE
CPDB: Add Geometry Columns to CSVs

### ISSUE THREAD

**Issue by alexrichey** [NYCPlanning/data-engineering#988]
Hey, @TangoYankee can you fill in the requirements here? In particular the csvs for which you need geo columns?

cc @fvankrieken and @damonmcc (can't recall which of you is the subject matter expert for CPDB, so tagging you both.)

**Comment by TangoYankee** [comment]
Thank you for making this filler ticket! I'll be organizing my thoughts into a larger discussion on the ae-data-flow repo. I'll follow up when my thoughts are more in order

**Comment by TangoYankee** [comment]
Okay... four months later... AE was able to keep the ability to parse shape files. We're okay without adding geometry columns to csvs.
